import { appRuntime } from "../network/api-client";
import type {
  BootstrapConfig,
  SemanticPalette,
  SupportedLocale,
} from "./bootstrap.schema";
import { normalizeMessages } from "./localization";

const light: SemanticPalette = {
  primary: "#F0B90B",
  onPrimary: "#181A20",
  background: "#F5F5F5",
  surface: "#FFFFFF",
  surfaceVariant: "#F0F1F2",
  text: "#1E2329",
  textMuted: "#707A8A",
  border: "#EAECEF",
  success: "#0ECB81",
  warning: "#D0980B",
  danger: "#F6465D",
  info: "#3861FB",
  pricePositive: "#0ECB81",
  priceNegative: "#F6465D",
  risk: "#D0980B",
  focus: "#FCD535",
  backdrop: "rgba(24,26,32,0.56)",
};

const dark: SemanticPalette = {
  primary: "#F0B90B",
  onPrimary: "#181A20",
  background: "#0B0E11",
  surface: "#181A20",
  surfaceVariant: "#23262D",
  text: "#EAECEF",
  textMuted: "#848E9C",
  border: "#2B3139",
  success: "#0ECB81",
  warning: "#F0B90B",
  danger: "#F6465D",
  info: "#4A7DFF",
  pricePositive: "#0ECB81",
  priceNegative: "#F6465D",
  risk: "#F0B90B",
  focus: "#FCD535",
  backdrop: "rgba(0,0,0,0.72)",
};

const zhCN = {
  "app.name": "AnyFun",
  "home.update": "应用升级",
  "home.market": "市场行情",
  "home.predict": "热门预测",
  "home.viewAll": "查看全部",
  "home.dexHotTokens": "DEX 热门代币",
  "home.deposit": "充值",
  "home.withdraw": "提现",
  "home.transfer": "划转",
  "home.support": "帮助与客服",
  "home.search": "搜索市场、代币",
  "home.scan": "扫描二维码",
  "home.notifications": "通知",
  "home.quick.predict": "预测市场",
  "home.quick.swap": "兑换",
  "home.quick.rank": "排行榜",
  "home.quick.invite": "邀请返佣",
  "home.quick.help": "帮助",
  "home.quick.more": "更多",
  "home.portfolio": "总资产估值",
  "home.hideBalance": "隐藏资产余额",
  "home.showBalance": "显示资产余额",
  "action.refresh": "刷新配置",
  "action.checkupdate": "检查更新",
  "action.retry": "重新下载",
  "action.details": "查看详情",
  "action.collapse": "收起详情",
  "action.settings": "设置",
  "action.back": "返回",
  "action.close": "关闭",
  "action.later": "稍后处理",
  "theme.system": "跟随系统",
  "theme.light": "浅色",
  "theme.dark": "深色",
  "status.loading": "正在同步应用配置",
  "status.error": "暂时无法获取远程配置",
  "update.none": "当前已经是最新版本",
  "update.optional": "发现可选更新",
  "update.recommended": "建议升级到最新版本",
  "update.required": "当前版本必须升级后继续使用",
  "update.releaseControl": "升级中心",
  "update.policy": "版本策略",
  "update.currentVersion": "当前版本",
  "update.currentVersionHint":
    "版本会在启动时自动检查，更新前会展示下载和安装状态。",
  "update.versionDetails": "版本详情",
  "update.info": "信息",
  "update.minimumVersion": "最低支持",
  "update.latestVersion": "最新版本",
  "update.channel": "分发通道",
  "update.release": "发布记录",
  "update.requestId": "请求编号",
  "update.otaTitle": "JS 与资源热更新",
  "update.runtime": "运行时版本",
  "update.checking": "检查中…",
  "update.otaAvailable": "发现兼容更新，准备下载",
  "update.otaDownloading": "正在下载 OTA 更新",
  "update.otaApplying": "正在重启并应用 OTA",
  "update.otaImmediateConfirm":
    "此更新标记为立即应用，只有在你确认后才会重启应用。",
  "update.otaImmediateRequired":
    "更新已下载完成，为保证应用正常运行，需要立即重启应用。重启预计需要几秒钟，请点击下方按钮继续。",
  "update.otaImmediateRequiredLabel": "必须完成更新",
  "update.otaImmediateHint": "请保持网络连接，重启期间请勿退出应用。",
  "update.otaImmediateTitle": "更新已准备好",
  "update.otaImmediateRetryTitle": "更新未应用",
  "update.otaImmediateRetry": "应用更新时遇到问题，请再次点击重启并更新。",
  "update.apply": "重启并应用 OTA",
  "update.applyImmediate": "确认并重启应用",
  "update.rollbackApply": "重启并回到安全版本",
  "update.otaDisabled": "OTA 已被远程策略关闭",
  "update.otaUnavailable": "当前构建未启用 OTA，请使用开发构建或发布版本验证。",
  "update.otaIncompatible": "当前通道或运行时没有兼容的 OTA",
  "update.otaCurrent": "当前已是最新兼容版本",
  "update.otaReadyNextLaunch": "更新已下载，将在下次启动时自动应用",
  "update.otaReadyImmediate": "更新已下载，可由你确认后立即重启应用",
  "update.otaRollback": "检测到 OTA 回退，当前使用安全版本",
  "update.embedded": "内置版本",
  "update.embeddedCurrent": "当前使用 APK 内置版本",
  "update.otaError": "暂时无法检查 OTA，请稍后重试。",
  "update.fullTitle": "全量更新",
  "update.fullDescription":
    "通过当前分发渠道安装签名版本，更新前请确认版本与来源。",
  "update.diagnostics": "诊断信息",
  "update.details": "升级详情",
  "update.notConfigured": "尚未配置",
  "update.fullOpened": "已打开当前分发渠道的升级入口",
  "update.fullUnavailable": "当前分发渠道尚未配置可安装地址",
  "update.apkDownloadTitle": "正在准备应用升级",
  "update.apkDownloading": "正在安全下载完整安装包，请保持网络连接。",
  "update.apkDownloadError": "安装包下载失败，请检查网络后重试。",
  "update.apkInstallerOpened": "安装包已下载，已打开系统安装确认页面。",
  "settings.title": "设置",
  "settings.theme": "主题",
  "settings.language": "语言",
  "settings.updateCenter": "升级中心",
  "settings.enabled": "已启用",
  "settings.section.general": "通用",
  "settings.section.notifications": "通知",
  "settings.section.trading": "交易偏好",
  "settings.section.security": "安全",
  "settings.section.about": "关于",
  "settings.colorScheme": "涨跌颜色",
  "settings.quoteCurrency": "计价货币",
  "settings.notifications": "推送通知",
  "settings.notificationsOff": "未开启",
  "settings.predictConfirm": "预测下单前确认",
  "settings.predictOrderType": "预测默认订单类型",
  "settings.dexSlippage": "兑换默认滑点",
  "settings.dexRiskWarning": "高风险代币提醒",
  "settings.securityCenter": "安全中心",
  "settings.checkUpdate": "检查更新",
  "settings.terms": "用户协议",
  "settings.privacy": "隐私政策",
  "settings.clearCache": "清除缓存",
  "settings.followSystemLanguage": "跟随系统语言",
  "settings.languageSwitchRetry": "语言未切换，检查网络后可再次点击重试。",
  "settings.colorSchemeHint":
    "行情、资产盈亏和 K 线使用该颜色方案；预测 Yes/No 语义色保持不变。",
  "predict.event.title": "事件详情",
  "predict.event.trading": "交易中",
  "predict.event.probability": "当前概率",
  "predict.event.orderbook": "盘口",
  "predict.event.rules": "规则",
  "predict.buyYes": "买入 Yes",
  "predict.buyNo": "买入 No",
  "predict.order.title": "确认预测订单",
  "predict.order.market": "预测市场",
  "predict.order.amount": "下单金额",
  "predict.order.estimated": "预计获得",
  "predict.order.confirm": "确认下单",
  "predict.settlement.title": "结算结果",
  "predict.settlement.settled": "已结算",
  "predict.settlement.description": "本次预测订单已完成结算",
  "predict.settlement.result": "结果",
  "predict.settlement.won": "预测成功",
  "predict.settlement.payout": "结算金额",
  "predict.settlement.done": "完成",
  "dex.token.chain": "网络",
  "dex.token.stats": "代币数据",
  "dex.token.marketCap": "市值",
  "dex.token.liquidity": "流动性",
  "dex.token.volume": "24h 成交",
  "dex.token.security": "安全检测",
  "dex.token.swap": "兑换此代币",
  "swap.history.title": "兑换记录",
  "swap.status.confirming": "确认中",
  "swap.status.success": "成功",
  "swap.status.failed": "失败",
  "assets.transfer": "划转",
  "assets.transfer.from": "从",
  "assets.transfer.to": "到",
  "assets.transfer.amount": "划转数量",
  "assets.transfer.available": "可用",
  "assets.transfer.confirm": "确认划转",
  "assets.accountDetail": "账户详情",
  "assets.locked": "锁定资产",
  "notif.title": "推送通知",
  "notif.orderFilled": "订单成交",
  "notif.predictSettled": "预测结算",
  "notif.predictClaimable": "可领取收益",
  "notif.swapResult": "兑换完成 / 失败",
  "notif.priceAlert": "价格提醒",
  "notif.promo": "活动与公告",
  "notif.security": "安全提醒",
  "about.title": "关于",
  "about.versionDetails": "版本详情",
  "about.upToDate": "当前已经是最新版本",
  "security.title": "安全中心",
  "security.level": "安全等级",
  "security.level.high": "高",
  "security.protections": "项保护措施已开启",
  "security.password": "登录密码",
  "security.email": "邮箱",
  "security.totp": "谷歌验证器",
  "security.bound": "已绑定",
  "security.antiPhishing": "反钓鱼码",
  "security.notSet": "未设置",
  "security.devices": "设备管理",
  "security.loginHistory": "登录记录",
  "security.addressBook": "提现地址簿",
  "nav.home": "首页",
  "nav.predict": "预测",
  "nav.positions": "持仓",
  "nav.dex": "DEX",
  "nav.market": "行情",
  "nav.swap": "兑换",
  "nav.assets": "资产",
  "nav.profile": "我的",
  "module.predict.title": "预测市场",
  "module.predict.description": "浏览事件概率、盘口和持仓机会。",
  "module.predict.eyebrow": "PREDICT",
  "module.predict.next": "市场列表、事件详情和下单能力将在业务接口接入后开放。",
  "module.positions.title": "预测持仓",
  "module.positions.description": "查看进行中、可领取和争议中的预测持仓。",
  "module.dex.title": "DEX",
  "module.dex.description": "浏览链上行情和兑换机会。",
  "module.dex.eyebrow": "DEX / ON-CHAIN",
  "module.dex.next": "行情、报价、风险检测和链上交易将在业务接口接入后开放。",
  "module.market.title": "行情",
  "module.market.description": "查看多链代币价格、涨跌和流动性。",
  "module.swap.title": "兑换",
  "module.swap.description": "在 DEX 钱包中进行链上资产兑换。",
  "module.predict.filter.hot": "热门",
  "module.predict.filter.breaking": "突发",
  "module.predict.filter.new": "新上线",
  "module.predict.filter.crypto": "加密",
  "module.predict.filter.sports": "体育",
  "module.predict.buyYes": "买 Yes",
  "module.predict.buyNo": "买 No",
  "module.predict.buy": "买",
  "module.positions.status.claimable": "可领取",
  "module.positions.status.disputed": "争议中",
  "module.positions.status.trading": "交易中",
  "module.positions.shares": "份",
  "module.dex.filter.allChains": "全部链",
  "module.dex.filter.bsc": "BSC",
  "module.dex.filter.ethereum": "Ethereum",
  "module.dex.tab.hot": "热门",
  "module.dex.tab.gainers": "涨幅榜",
  "module.dex.tab.new": "新币",
  "module.dex.tab.watchlist": "自选",
  "module.dex.liquidity": "流动性",
  "module.swap.pay": "支付",
  "module.swap.receiveEstimated": "获得（预估）",
  "module.swap.balancePrefix": "余额",
  "module.swap.detail.rate": "汇率",
  "module.swap.detail.priceImpact": "价格影响",
  "module.swap.detail.minimumReceived": "最少获得",
  "module.swap.detail.slippage": "滑点",
  "module.swap.detail.networkFee": "网络费",
  "module.swap.detail.serviceFee": "服务费",
  "module.swap.submit": "兑换",
  "module.preview.title": "模块已启用",
  "module.preview.description": "当前页面结构已根据租户应用配置生成。",
  "module.preview.status": "接入状态",
  "module.preview.integrationTitle": "业务服务待接入",
  "module.preview.integrationDescription":
    "模块开关、主题、语言和版本已由服务端配置中心统一下发。",
  "module.preview.next": "下一步",
  "assets.eyebrow": "PORTFOLIO",
  "assets.title": "我的资产",
  "assets.subtitle": "跨网络查看余额、估值和今日变化。",
  "assets.total": "总资产",
  "assets.today": "今日收益",
  "assets.available": "可用资产",
  "assets.networks": "已连接网络",
  "assets.holdings": "资产明细",
  "assets.accounts": "账户",
  "assets.fundingAccount": "资金账户",
  "assets.predictAccount": "预测账户",
  "assets.dexWallet": "DEX 钱包",
  "assets.updated": "刚刚更新",
  "profile.eyebrow": "ACCOUNT",
  "profile.title": "个人中心",
  "profile.subtitle": "管理账户偏好、安全状态和应用更新。",
  "profile.preferences": "偏好与应用",
  "profile.settingsHint": "语言、主题与应用偏好设置",
  "profile.updateHint": "查看全量更新与 OTA 状态",
  "profile.security": "设备与安全",
  "profile.securityCenter": "安全中心",
  "profile.securityHint": "查看设备、保护措施和钱包安全状态",
  "profile.network": "当前网络",
  "profile.quickActions": "快捷入口",
  "profile.more": "更多",
  "profile.account": "账户",
  "profile.mine": "我的",
  "profile.verified": "已认证 · L2",
  "profile.identity": "身份认证",
  "profile.invite": "邀请返佣",
  "profile.help": "帮助客服",
  "profile.transactionHistory": "交易记录",
  "profile.invitedCount": "已邀请 12 人",
  "settings.notificationsEnabled": "更新通知已开启",
  "update.noticeTitle": "发现新版本",
  "update.noticeDescription": "新版本已准备好，可查看更新内容后选择升级。",
  "update.viewNow": "查看更新",
  "update.confirmAndDownload": "确认并下载",
  "update.localizationTitle": "语言资源已更新",
  "update.localizationDescription": "新的语言包已准备好，将在下次刷新后生效。",
  "update.brandingTitle": "品牌配置已更新",
  "update.brandingDescription": "新的品牌资源已准备好，将在下次启动时生效。",
  "update.configTitle": "应用配置已更新",
  "update.configDescription": "应用配置已更新，正在后台同步。",
};

const enUS: Record<keyof typeof zhCN, string> = {
  "app.name": "AnyFun",
  "home.update": "App updates",
  "home.market": "Market",
  "home.predict": "Popular predictions",
  "home.viewAll": "View all",
  "home.dexHotTokens": "DEX hot tokens",
  "home.deposit": "Deposit",
  "home.withdraw": "Withdraw",
  "home.transfer": "Transfer",
  "home.support": "Help and support",
  "home.search": "Search markets and tokens",
  "home.scan": "Scan QR code",
  "home.notifications": "Notifications",
  "home.quick.predict": "Predictions",
  "home.quick.swap": "Swap",
  "home.quick.rank": "Leaderboard",
  "home.quick.invite": "Referral",
  "home.quick.help": "Help",
  "home.quick.more": "More",
  "home.portfolio": "Total portfolio value",
  "home.hideBalance": "Hide asset balance",
  "home.showBalance": "Show asset balance",
  "action.refresh": "Refresh configuration",
  "action.checkupdate": "Check for updates",
  "action.retry": "Download again",
  "action.details": "View details",
  "action.collapse": "Hide details",
  "action.settings": "Settings",
  "action.back": "Back",
  "action.close": "Close",
  "action.later": "Later",
  "theme.system": "System",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "status.loading": "Syncing app configuration",
  "status.error": "Remote configuration is temporarily unavailable",
  "update.none": "You already have the latest version",
  "update.optional": "An optional update is available",
  "update.recommended": "Updating to the latest version is recommended",
  "update.required": "Update is required to continue",
  "update.releaseControl": "Update center",
  "update.policy": "Version policy",
  "update.currentVersion": "Current version",
  "update.currentVersionHint":
    "The app checks for updates when it starts and shows download and install progress before applying one.",
  "update.versionDetails": "Version details",
  "update.info": " info",
  "update.minimumVersion": "Minimum supported",
  "update.latestVersion": "Latest version",
  "update.channel": "Distribution channel",
  "update.release": "Release",
  "update.requestId": "Request ID",
  "update.otaTitle": "JS and asset hot update",
  "update.runtime": "Runtime version",
  "update.checking": "Checking…",
  "update.otaAvailable": "A compatible update is available",
  "update.otaDownloading": "Downloading OTA update",
  "update.otaApplying": "Restarting to apply OTA",
  "update.otaImmediateConfirm":
    "This update is marked for immediate application. The app will restart only after you confirm.",
  "update.otaImmediateRequired":
    "The update is ready and requires an immediate restart. This should take a few seconds; tap the button below to continue.",
  "update.otaImmediateRequiredLabel": "Update required",
  "update.otaImmediateHint":
    "Keep your network connection available and do not close the app while it restarts.",
  "update.otaImmediateTitle": "Update ready",
  "update.otaImmediateRetryTitle": "Update not applied",
  "update.otaImmediateRetry":
    "The update could not be applied. Tap the button to retry restarting and applying it.",
  "update.apply": "Restart and apply OTA",
  "update.applyImmediate": "Confirm and restart app",
  "update.rollbackApply": "Restart and return to the safe version",
  "update.otaDisabled": "OTA is disabled by remote policy",
  "update.otaUnavailable":
    "OTA is unavailable in this build. Use a development or release build.",
  "update.otaIncompatible":
    "No compatible OTA exists for this channel and runtime",
  "update.otaCurrent": "This runtime is up to date",
  "update.otaReadyNextLaunch":
    "Update downloaded and will be applied on the next launch",
  "update.otaReadyImmediate":
    "Update downloaded and can be applied after you confirm a restart",
  "update.otaRollback":
    "An OTA rollback was detected; the safe version is active",
  "update.embedded": "Embedded version",
  "update.embeddedCurrent": "Running the version embedded in this build",
  "update.otaError": "Unable to check OTA right now. Try again later.",
  "update.fullTitle": "Full update",
  "update.fullDescription":
    "Install a signed version through the current distribution channel.",
  "update.diagnostics": "Diagnostics",
  "update.details": "Update details",
  "update.notConfigured": "Not configured",
  "update.fullOpened": "Opened the update entry for this distribution channel",
  "update.fullUnavailable":
    "No install URL is configured for this distribution channel",
  "update.apkDownloadTitle": "Preparing app update",
  "update.apkDownloading":
    "Downloading the signed APK. Keep the network connection active.",
  "update.apkDownloadError":
    "The APK download failed. Check your connection and try again.",
  "update.apkInstallerOpened":
    "The APK is ready and the system installation confirmation was opened.",
  "settings.title": "Settings",
  "settings.theme": "Theme",
  "settings.language": "Language",
  "settings.updateCenter": "Update center",
  "settings.enabled": "Enabled",
  "settings.section.general": "General",
  "settings.section.notifications": "Notifications",
  "settings.section.trading": "Trading preferences",
  "settings.section.security": "Security",
  "settings.section.about": "About",
  "settings.colorScheme": "Price colors",
  "settings.quoteCurrency": "Quote currency",
  "settings.notifications": "Push notifications",
  "settings.notificationsOff": "Off",
  "settings.predictConfirm": "Confirm prediction orders",
  "settings.predictOrderType": "Default prediction order type",
  "settings.dexSlippage": "Default swap slippage",
  "settings.dexRiskWarning": "High-risk token warning",
  "settings.securityCenter": "Security center",
  "settings.checkUpdate": "Check for updates",
  "settings.terms": "Terms of service",
  "settings.privacy": "Privacy policy",
  "settings.clearCache": "Clear cache",
  "settings.followSystemLanguage": "Follow system language",
  "settings.languageSwitchRetry":
    "The language was not changed. Check your connection and try again.",
  "settings.colorSchemeHint":
    "Markets, asset PnL and charts use this scheme. Prediction Yes/No colors remain semantic.",
  "predict.event.title": "Event details",
  "predict.event.trading": "Trading",
  "predict.event.probability": "Current probability",
  "predict.event.orderbook": "Order book",
  "predict.event.rules": "Rules",
  "predict.buyYes": "Buy Yes",
  "predict.buyNo": "Buy No",
  "predict.order.title": "Confirm prediction order",
  "predict.order.market": "Prediction market",
  "predict.order.amount": "Order amount",
  "predict.order.estimated": "Estimated payout",
  "predict.order.confirm": "Confirm order",
  "predict.settlement.title": "Settlement result",
  "predict.settlement.settled": "Settled",
  "predict.settlement.description": "This prediction order has been settled",
  "predict.settlement.result": "Result",
  "predict.settlement.won": "Prediction won",
  "predict.settlement.payout": "Payout",
  "predict.settlement.done": "Done",
  "dex.token.chain": "Network",
  "dex.token.stats": "Token data",
  "dex.token.marketCap": "Market cap",
  "dex.token.liquidity": "Liquidity",
  "dex.token.volume": "24h volume",
  "dex.token.security": "Security checks",
  "dex.token.swap": "Swap this token",
  "swap.history.title": "Swap history",
  "swap.status.confirming": "Confirming",
  "swap.status.success": "Success",
  "swap.status.failed": "Failed",
  "assets.transfer": "Transfer",
  "assets.transfer.from": "From",
  "assets.transfer.to": "To",
  "assets.transfer.amount": "Transfer amount",
  "assets.transfer.available": "Available",
  "assets.transfer.confirm": "Confirm transfer",
  "assets.accountDetail": "Account details",
  "assets.locked": "Locked assets",
  "notif.title": "Push notifications",
  "notif.orderFilled": "Order filled",
  "notif.predictSettled": "Prediction settled",
  "notif.predictClaimable": "Claimable return",
  "notif.swapResult": "Swap completed / failed",
  "notif.priceAlert": "Price alerts",
  "notif.promo": "Promotions and announcements",
  "notif.security": "Security alerts",
  "about.title": "About",
  "about.versionDetails": "Version details",
  "about.upToDate": "You are up to date",
  "security.title": "Security center",
  "security.level": "Security level",
  "security.level.high": "High",
  "security.protections": "protections enabled",
  "security.password": "Password",
  "security.email": "Email",
  "security.totp": "Authenticator",
  "security.bound": "Bound",
  "security.antiPhishing": "Anti-phishing code",
  "security.notSet": "Not set",
  "security.devices": "Device management",
  "security.loginHistory": "Login history",
  "security.addressBook": "Withdrawal address book",
  "nav.home": "Home",
  "nav.predict": "Predict",
  "nav.positions": "Positions",
  "nav.dex": "DEX",
  "nav.market": "Markets",
  "nav.swap": "Swap",
  "nav.assets": "Assets",
  "nav.profile": "Profile",
  "module.predict.title": "Prediction markets",
  "module.predict.description":
    "Browse event probabilities, books and positions.",
  "module.predict.eyebrow": "PREDICT",
  "module.predict.next":
    "Market lists, event details and order flows will open after the business APIs are connected.",
  "module.positions.title": "Prediction positions",
  "module.positions.description":
    "Review active, claimable and disputed positions.",
  "module.dex.title": "DEX",
  "module.dex.description": "Browse on-chain markets and swap opportunities.",
  "module.dex.eyebrow": "DEX / ON-CHAIN",
  "module.dex.next":
    "Markets, quotes, risk checks and on-chain trading will open after the business APIs are connected.",
  "module.market.title": "Markets",
  "module.market.description":
    "Review multi-chain prices, moves and liquidity.",
  "module.swap.title": "Swap",
  "module.swap.description": "Swap assets on-chain from the DEX wallet.",
  "module.predict.filter.hot": "Hot",
  "module.predict.filter.breaking": "Breaking",
  "module.predict.filter.new": "New",
  "module.predict.filter.crypto": "Crypto",
  "module.predict.filter.sports": "Sports",
  "module.predict.buyYes": "Buy Yes",
  "module.predict.buyNo": "Buy No",
  "module.predict.buy": "Buy",
  "module.positions.status.claimable": "Claimable",
  "module.positions.status.disputed": "Disputed",
  "module.positions.status.trading": "Trading",
  "module.positions.shares": "shares",
  "module.dex.filter.allChains": "All chains",
  "module.dex.filter.bsc": "BSC",
  "module.dex.filter.ethereum": "Ethereum",
  "module.dex.tab.hot": "Hot",
  "module.dex.tab.gainers": "Top gainers",
  "module.dex.tab.new": "New",
  "module.dex.tab.watchlist": "Watchlist",
  "module.dex.liquidity": "Liquidity",
  "module.swap.pay": "Pay",
  "module.swap.receiveEstimated": "Receive (estimated)",
  "module.swap.balancePrefix": "Balance",
  "module.swap.detail.rate": "Rate",
  "module.swap.detail.priceImpact": "Price impact",
  "module.swap.detail.minimumReceived": "Minimum received",
  "module.swap.detail.slippage": "Slippage",
  "module.swap.detail.networkFee": "Network fee",
  "module.swap.detail.serviceFee": "Service fee",
  "module.swap.submit": "Swap",
  "module.preview.title": "Module enabled",
  "module.preview.description":
    "This page structure is generated from the tenant app configuration.",
  "module.preview.status": "Integration status",
  "module.preview.integrationTitle": "Business service pending",
  "module.preview.integrationDescription":
    "Module flags, theme, language and version are delivered by the server configuration center.",
  "module.preview.next": "Next",
  "assets.eyebrow": "PORTFOLIO",
  "assets.title": "My assets",
  "assets.subtitle": "Review balances, value and daily moves across networks.",
  "assets.total": "Total assets",
  "assets.today": "Today's return",
  "assets.available": "Available",
  "assets.networks": "Networks",
  "assets.holdings": "Holdings",
  "assets.accounts": "Accounts",
  "assets.fundingAccount": "Funding account",
  "assets.predictAccount": "Prediction account",
  "assets.dexWallet": "DEX wallet",
  "assets.updated": "Updated now",
  "profile.eyebrow": "ACCOUNT",
  "profile.title": "Profile",
  "profile.subtitle": "Manage preferences, security status and app updates.",
  "profile.preferences": "Preferences and app",
  "profile.settingsHint": "Language, theme and app preferences",
  "profile.updateHint": "View full releases and OTA status",
  "profile.security": "Device and security",
  "profile.securityCenter": "Security center",
  "profile.securityHint": "Review devices, protections and wallet security",
  "profile.network": "Current network",
  "profile.quickActions": "Quick actions",
  "profile.more": "More",
  "profile.account": "Account",
  "profile.mine": "My assets",
  "profile.verified": "Verified · L2",
  "profile.identity": "Identity verification",
  "profile.invite": "Referral",
  "profile.help": "Help and support",
  "profile.transactionHistory": "Transaction history",
  "profile.invitedCount": "12 invited",
  "settings.notificationsEnabled": "Update notifications enabled",
  "update.noticeTitle": "New version available",
  "update.noticeDescription":
    "A new version is ready. Review the changes before updating.",
  "update.viewNow": "View update",
  "update.confirmAndDownload": "Confirm and download",
  "update.localizationTitle": "Language resources updated",
  "update.localizationDescription":
    "New language resources are ready and will apply after the next refresh.",
  "update.brandingTitle": "Branding updated",
  "update.brandingDescription":
    "New branding resources are ready and will apply on the next launch.",
  "update.configTitle": "App configuration updated",
  "update.configDescription":
    "App configuration changed and is syncing in the background.",
};

export function createFallbackConfig(locale: SupportedLocale): BootstrapConfig {
  return {
    schemaVersion: 1,
    configVersion: "embedded-1",
    generatedAt: "2026-08-21T00:00:00.000Z",
    ttlSeconds: 300,
    requestId: "offline",
    localization: {
      selectedLocale: locale,
      fallbackLocale: "zh-CN",
      supportedLocales: ["zh-CN", "en-US"],
      localeCatalog: [
        { code: "zh-CN", label: "简体中文", nativeName: "中文" },
        { code: "en-US", label: "English", nativeName: "English" },
      ],
      messagesVersion: "embedded-1",
      messages: normalizeMessages(locale === "en-US" ? enUS : zhCN),
    },
    theme: {
      defaultMode: "system",
      allowUserOverride: true,
      paletteVersion: "embedded-trading-1",
      light,
      dark,
    },
    modules: { predict: true, dex: true },
    branding: {
      schemaVersion: 1,
      version: 1,
      enabled: true,
      selectedLocale: locale,
      fallbackLocale: "zh-CN",
      launch: {
        enabled: true,
        minDisplayMs: 700,
        maxDisplayMs: 1800,
        animation: { type: "fade_scale", durationMs: 360 },
        title: locale === "en-US" ? "AnyFun" : "AnyFun",
        subtitle:
          locale === "en-US" ? "Syncing app configuration" : "正在同步应用配置",
        visuals: {
          light: { backgroundColor: light.background },
          dark: { backgroundColor: dark.background },
        },
      },
      cachePolicy: {
        maxBytes: 20 * 1024 * 1024,
        keepVersions: 2,
        staleAfterSeconds: 7 * 24 * 60 * 60,
      },
    },
    features: {
      updateCenter: true,
      otaEnabled: false,
      directUpdateEnabled: appRuntime.platform === "android",
      diagnosticsEnabled: true,
    },
    app: {
      version: appRuntime.version,
      buildNumber: appRuntime.buildNumber,
      platform: appRuntime.platform,
      distribution:
        appRuntime.distributionChannel as BootstrapConfig["app"]["distribution"],
      runtimeVersion: appRuntime.runtimeVersion,
    },
    update: {
      decision: "none",
      minSupportedVersion: appRuntime.version,
      latestVersion: appRuntime.version,
      releaseNotes: [],
      ota: {
        enabled: false,
        channel: "embedded",
        runtimeVersion: appRuntime.runtimeVersion,
        applyStrategy: "next_launch",
        revision: null,
        updateId: null,
        baseReleaseId: null,
        releaseNotes: [],
      },
      full: {
        channel: "development",
        actionUrl: null,
        releaseId: null,
        sha256: null,
        size: null,
      },
    },
    support: {
      diagnosticId: "offline",
      statusPageUrl: "https://status.example.com",
    },
  };
}
