import { appRuntime } from "../network/api-client";
import type {
  BootstrapConfig,
  SemanticPalette,
  SupportedLocale,
} from "./bootstrap.schema";
import { normalizeMessages } from "./localization";

const light: SemanticPalette = {
  primary: "#F0B90B",
  onPrimary: "#181A20",
  background: "#F5F5F5",
  surface: "#FFFFFF",
  surfaceVariant: "#F0F1F2",
  text: "#1E2329",
  textMuted: "#707A8A",
  border: "#EAECEF",
  success: "#0ECB81",
  warning: "#D0980B",
  danger: "#F6465D",
  info: "#3861FB",
  pricePositive: "#0ECB81",
  priceNegative: "#F6465D",
  risk: "#D0980B",
  focus: "#FCD535",
  backdrop: "rgba(24,26,32,0.56)",
};

const dark: SemanticPalette = {
  primary: "#F0B90B",
  onPrimary: "#181A20",
  background: "#0B0E11",
  surface: "#181A20",
  surfaceVariant: "#23262D",
  text: "#EAECEF",
  textMuted: "#848E9C",
  border: "#2B3139",
  success: "#0ECB81",
  warning: "#F0B90B",
  danger: "#F6465D",
  info: "#4A7DFF",
  pricePositive: "#0ECB81",
  priceNegative: "#F6465D",
  risk: "#F0B90B",
  focus: "#FCD535",
  backdrop: "rgba(0,0,0,0.72)",
};

const zhCN = {
  "app.name": "AnyFun",
  "home.update": "应用升级",
  "home.market": "市场行情",
  "home.predict": "热门预测",
  "home.viewAll": "查看全部",
  "home.dexHotTokens": "DEX 热门代币",
  "home.deposit": "充值",
  "home.withdraw": "提现",
  "home.transfer": "划转",
  "home.support": "帮助与客服",
  "home.connectWallet": "连接钱包",
  "home.walletAccount": "钱包账户",
  "home.predictAccount": "预测账户",
  "home.claimable": "可领取",
  "home.volume": "成交",
  "home.closesIn": "截止",
  "home.outcomes": "{n} 个结果",
  "login.welcome": "欢迎",
  "login.welcomeTitle": "连接钱包，开始预测与兑换",
  "login.welcomeHint":
    "无需注册，用你的钱包地址登录。行情与市场无需登录即可浏览。",
  "login.createWallet": "创建新钱包",
  "login.createHint": "一分钟完成，助记词加密存于本机",
  "login.importWallet": "导入已有钱包",
  "login.importHint": "助记词或私钥",
  "login.useWallet": "使用内置钱包",
  "login.useWalletHint": "用本机保管的钱包签名登录",
  "login.unavailable": "租户未启用",
  "login.notInstalled": "未安装 · 点击后扫码连接",
  "login.opening": "正在打开 {wallet}…",
  "login.connectFailed": "连接 {wallet} 没有成功，请重试",
  "login.connectTimeout": "等待 {wallet} 确认超时，请重试",
  "login.noEnabledChain":
    "{wallet} 批准的网络都未在本平台启用，请在钱包里切换到已支持的网络后重试",

  "login.reason": "确认登录签名",
  "login.builtin": "内置钱包",
  "login.external": "连接外部钱包",
  "login.installed": "已安装",
  "login.otherWallet": "其他钱包",
  "login.otherHint": "扫码连接 · WalletConnect",
  "login.terms": "继续即表示同意用户协议与隐私政策",
  "login.continueTo": "登录后继续{action}",
  "login.intent.order": "买入 {outcome}",
  "login.intent.swap": "兑换",
  "login.intent.transfer": "划转",
  "login.intent.assets": "查看资产",
  "login.intent.positions": "查看持仓",
  "login.intent.watchlist": "同步自选",
  "login.confirmTitle": "确认登录",
  "login.connected": "{wallet} 已连接",
  "login.signTo": "登录到",
  "login.purpose": "用途",
  "login.purposeValue": "验证你拥有该地址",
  "login.validity": "有效期",
  "login.validityValue": "7 天 · 可随时退出",
  "login.fee": "费用",
  "login.feeValue": "免费 · 不发起链上交易",
  "login.signNote": "签名不会授权任何转账。请确认域名与你打开的 App 一致。",
  "login.signAndLogin": "签名并登录",
  "login.switchWallet": "换一个钱包",
  "login.signing": "等待钱包签名…",
  "login.cancelled": "已取消登录",
  "login.timeout": "钱包未响应，可换一个钱包重试",
  "login.success": "登录成功",
  "login.balance": "余额",
  "account.title": "钱包账户",
  "account.current": "当前",
  "account.copy": "复制地址",
  "account.copied": "地址已复制",
  "common.copyFailed": "复制没成功，请手动选择文本",
  "account.disconnect": "断开连接",
  "account.disconnected": "已断开连接",
  "account.disconnectFailed": "断开没成功，请重试",
  "account.addWallet": "添加钱包",
  "account.notBackedUp": "未备份",
  "common.close": "关闭",
  "common.cancel": "取消",
  "common.confirm": "确认",
  "common.done": "完成",
  "common.max": "最大",
  "assets.totalValue": "总资产估值",
  "assets.today": "今日",
  "assets.receive": "收款",
  "assets.send": "转出",
  "assets.transferAction": "划转",
  "assets.swap": "兑换",
  "assets.accounts": "账户",
  "assets.wallet": "钱包",
  "assets.predictAccount": "预测账户",
  "assets.chains": "{n} 条链",
  "assets.available": "可用",
  "assets.coins": "币种",
  "assets.hideSmall": "隐藏小额",
  "assets.lockedInOrders": "挂单占用",
  "assets.accountTotal": "账户总值",
  "assets.withdrawToWallet": "取回钱包",
  "assets.splitMerge": "拆分 / 合并",
  "assets.custody": "资产由链上合约托管，地址 {address}",
  "assets.walletTotal": "钱包总值",
  "assets.allChains": "全部链",
  "assets.balanceUnavailable.node":
    "{chain} 的余额暂时拿不到：节点没有响应。其他链不受影响。",
  "assets.balanceUnavailable.endpoints":
    "{chain} 没有可用的节点，余额无法读取。其他链不受影响。",
  "assets.balanceUnavailable.retry": "重试",
  "assets.balanceUnavailable.catalogue":
    "{chain} 的代币目录不完整，余额暂不显示。其他链不受影响。",
  "assets.totalPartial": "部分合计：不含暂时不可用的链和没有估值的代币",

  "assets.signInToView": "登录后查看资产",
  "transfer.title": "划转",
  "transfer.from": "从",
  "transfer.to": "到",
  "transfer.token": "币种",
  "transfer.amount": "数量",
  "transfer.walletAvailable": "钱包可用 {amount}",
  "transfer.predictAvailable": "预测账户可用 {amount}",
  "transfer.networkFee": "网络费",
  "transfer.confirmDeposit": "确认存入 {amount}",
  "transfer.confirmWithdraw": "确认取出 {amount}",
  "transfer.depositTitle": "存入 {amount}",
  "transfer.insufficient": "余额不足",
  "transfer.swapDirection": "对调方向",
  "transfer.notEnabled": "预测账户还没启用，启用后才能划转。",
  "transfer.enableNow": "去启用",
  "transfer.asset": "转入币种",
  "transfer.gasBalance": "钱包 gas",
  "transfer.noGas": "钱包里的 {symbol} 不够付这次转入的手续费",
  "transfer.depositSteps.USDC":
    "2 笔链上交易：先授权 USDC，再包装成 USDW 存入预测账户，都由钱包地址付 gas。",
  "transfer.depositSteps.USDW":
    "1 笔链上交易：USDW 直接转入预测账户，由钱包地址付 gas。",
  "transfer.step.approve": "正在授权 USDC…",
  "transfer.step.wrap": "正在包装并存入…",
  "transfer.step.transfer": "正在转入…",
  "transfer.withdrawTwoPhase":
    "取回分两步：先发起解包，等待 {delay} 后领取，USDC 回到钱包地址 {address}。",
  "transfer.unwrapDelay": "等待时间",
  "transfer.minWithdraw": "最少取出 {amount}",
  "transfer.withdrawInitiated": "已发起取回，到期后在下方领取",
  "transfer.pendingTitle": "待领取",
  "transfer.noPending": "没有待领取的取回",
  "transfer.claimableIn": "{countdown} 后可领取",
  "transfer.claimReady": "可领取",
  "transfer.claim": "领取",
  "transfer.claimTitle": "领取 {amount}",
  "transfer.claimed": "已领取，USDC 已回到钱包",
  "transfer.pendingIndexing": "链上已发起，等待平台索引",
  "transfer.failed": "划转失败：",
  "transfer.faucet": "测试网 gas",
  "transfer.faucetClaim": "领取 {amount}",
  "transfer.faucetClaimed": "今日已领取",
  "transfer.faucetDone": "已领取测试网 gas",
  "transfer.faucetFailed": "领取测试网 gas 失败：",
  "transfer.walletAddress": "钱包地址",
  "assets.predictNotEnabled": "尚未启用 · 点击启用",
  "assets.enablePredict": "启用预测账户",
  "assets.safeBalance": "账户余额",
  "predict.enableChip": "启用",
  "predict.enable.title": "启用预测账户",
  "predict.enable.intro":
    "预测市场用一个由你的钱包地址控制的链上账户（Safe）持有 USDW 并撮合下单。启用需要用钱包签几次名，不花 gas；已完成的步骤不会重复。",
  "predict.enable.step.login": "登录平台（签名）",
  "predict.enable.step.deploySafe": "创建链上账户（Safe）",
  "predict.enable.step.clobKey": "生成交易凭证（签名）",
  "predict.enable.step.approve": "授权交易合约（签名）",
  "predict.enable.safe": "账户地址 {address}",
  "predict.enable.run": "开始启用",
  "predict.enable.resume": "继续启用",
  "predict.enable.complete": "已启用",
  "predict.enable.later": "稍后",
  "predict.enable.done": "预测账户已启用",
  "predict.enable.failed": "启用失败：",
  "predict.enable.notConfigured": "这个 App 还没接入预测市场平台，请联系运营。",
  "predict.enable.agreements": "平台协议",
  "predict.enable.agree": "我已阅读并同意以上协议",
  "predict.enable.view": "查看",
  "predict.enable.agreementRequired": "必读",
  "tx.signed": "已签名",
  "tx.submitted": "已提交",
  "tx.confirmed": "已确认",
  "tx.failed": "失败",
  "tx.reverted": "交易在链上被回滚，网络费已消耗",
  "tx.minimize": "最小化，继续浏览",
  "receive.title": "收款",
  "receive.copy": "复制地址",
  "receive.share": "分享",
  "receive.warn": "只向此地址转入 {chain} 网络的资产；其他网络转入将无法找回",
  "receive.support":
    "支持 {chain} 上的 {tokens} 及任意代币。到账通常需要 1–3 个区块确认。",
  "receive.copied": "已复制",
  "receive.testnetNotice":
    "这是测试网地址，测试网资产没有真实价值；请勿向它转入主网资产。",
  "receive.tokenSeparator": "、",
  "receive.noChain":
    "当前账户没有可收款的网络：钱包批准的网络都未在本平台启用。",
  "send.title": "转出",
  "send.address": "收款地址",
  "send.tokenContract": "代币合约",
  "send.nativeToken": "原生代币（无合约）",
  "send.impersonationWarning":
    "这不是平台核验的 {symbol}：它的合约地址与主流 {symbol} 不同。转出前请逐字核对上面的合约地址。",
  "send.checkAddress": "转出无法撤销。请逐字核对完整地址。",
  "send.addressPlaceholder": "粘贴或扫描地址",
  "send.paste": "粘贴",
  "send.clear": "清空",
  "send.recent": "最近转出",
  "send.recentEmpty":
    "还没有转出记录。转出过的地址会出现在这里，方便再次选用。",
  "send.pickToken": "选择要转出的币",
  "send.available": "可用",
  "send.noBalanceOnChain": "这条链上没有可转出的资产",
  "send.loadingBalances": "正在读取余额…",
  "send.scan": "扫码",
  "send.scanTitle": "扫描收款地址",
  "send.scanHint": "对准收款方的地址二维码",
  "send.scanNotAddress": "这个二维码里没有钱包地址",
  "send.scanTorch": "手电筒",
  "send.scanPermissionTitle": "需要相机权限",
  "send.scanPermissionBody":
    "扫描地址二维码需要使用相机。请在系统设置里允许本应用使用相机。",
  "send.scanOpenSettings": "去设置",
  "send.scanChainMismatch":
    "二维码标注的是 {scanned} 网络，当前选的币在 {current} 上。请与收款方核对在哪条链上收款。",
  "send.scanChainUnknown":
    "二维码标注的网络（chainId {chainId}）不在本平台启用的网络里，请与收款方核对。",
  "send.addressValid": "{chain} 地址格式校验通过",
  "send.addressInvalid": "地址格式不正确",
  "send.addressChecksum": "地址大小写校验和不正确，可能抄错了一个字符",
  "send.addressIsContract": "这是该代币自己的合约地址，转入的资产会永久丢失",
  "send.network": "网络",
  "send.amount": "数量",
  "send.balance": "余额 {amount}",
  "send.networkFee": "网络费",
  "send.eta": "预计到账",
  "send.etaValue": "约 15 秒",
  "send.recipientGets": "对方实收",
  "send.biometricHint": "超过 $1,000 的转出需要生物识别再次验证",
  "send.confirm": "确认转出 {amount}",
  "send.confirmTitle": "确认转出",
  "send.submitted": "已提交转出",
  "send.failed": "转出失败",
  "send.feeEstimating": "估算中…",
  "send.feeUnavailable": "暂不可估",
  "send.feeRequired": "手续费暂时无法估算，先不能转出。请稍后再试。",
  "send.demoLedger": "演示账本：这笔转出只记在本机，不会上链。",
  "send.testnetTag": "测试网",
  "send.noChain": "当前没有启用的网络，暂时无法转出。",
  "send.testnetNotice": "这是测试网，转出的代币没有真实价值。",
  "send.confirmInWallet": "已跳转到钱包 App，请在那里确认后返回。",
  "send.error.feeChanged": "网络费在你确认后明显上涨，已停止签名。请重新确认。",
  // 失败原因必须分开讲：最高频的困惑是"我有 USDT，为什么转不了"，
  // 答案是缺原生币付手续费，而不是余额不足
  "send.error.gas": "网络费要用 {symbol} 支付，余额不足。请先充入少量后重试。",
  "send.error.balance": "{symbol} 余额不足",
  "send.error.gasAnomaly":
    "{symbol} 的转账消耗异常，已阻止。这个代币合约可能有问题，请勿继续尝试。",
  "send.error.network": "连不上链上节点，请检查网络后重试",
  "send.error.node": "节点拒绝了这笔交易，请稍后重试",
  "send.error.chainEndpoints": "这条网络当前没有可用的节点，请稍后重试",
  "send.error.chainDisabled": "这条网络已在本平台停用",
  "send.error.tokenMismatch":
    "这个代币的合约信息与已知记录不符，已阻止转出。请联系客服核实。",
  "send.error.noKey":
    "这台设备上找不到该账户的密钥，无法签名。请重新导入钱包。",
  "send.error.rejected": "已取消，这笔转出没有发出",
  "send.error.authFailed": "身份验证未通过，这笔转出没有发出",
  "send.error.timeout": "钱包没有响应。请打开钱包 App 确认这笔请求",
  "send.error.unsafe": "交易参数不完整，已阻止签名。这笔转出没有发出",
  "predict.title": "预测市场",
  "predict.topUp": "去充值",
  "predict.sort.volume": "成交量",
  "predict.sort.endingSoon": "即将截止",
  "predict.sort.newest": "最新",
  "predict.special": "专场",
  "predict.outcomes": "{n} 个结果",
  "predict.volume": "成交 {amount}",
  "predict.holders": "{n} 人持仓",
  "predict.closesAt": "{time} 截止",
  "predict.closesIn": "{time}截止",
  "predict.closedAt": "已于 {time} 截止",
  "predict.kickoff": "{time} 开赛",
  "predict.draw": "平局",
  "predict.probability": "概率",
  "predict.yesProbability": "Yes 概率",
  "predict.buyYes": "买 Yes",
  "predict.buyNo": "买 No",
  "predict.buy": "买入",
  "predict.sell": "卖出",
  "predict.win1": "赢得 $1.00",
  "predict.maxReturn": "最多赢 {pct}",
  "predict.today": "今日",
  "predict.status.trading": "交易中",
  "predict.status.awaiting_result": "已截止 · 等待结果",
  "predict.status.result_proposed": "等待结果确认",
  "predict.status.disputed": "争议中",
  "predict.status.arbitrating": "等待商户裁决",
  "predict.status.settled": "已结算",
  "predict.tab.book": "盘口",
  "predict.tab.trades": "成交",
  "predict.tab.rules": "规则",
  "predict.tab.holders": "持有者",
  "predict.book.yes": "Yes 盘口",
  "predict.book.spread": "价差 {spread}",
  "predict.book.tick": "深度 {tick}",
  "predict.book.bid": "买价",
  "predict.book.ask": "卖价",
  "predict.book.shares": "份额",
  "predict.rules.title": "结算规则",
  "predict.rules.resolver": "裁决方",
  "predict.rules.resolverValue": "商户管理员",
  "predict.rules.disputeWindow": "争议期",
  "predict.rules.disputeWindowValue": "结果提交后 {hours} 小时",
  "predict.rules.fee": "手续费",
  "predict.rules.feeValue": "成交额 {pct}",
  "predict.order.market": "市价",
  "predict.order.limit": "限价",
  "predict.order.limitPrice": "限价（¢）",
  "predict.order.bookHint": "盘口 {bid} / {ask}",
  "predict.order.amount": "金额",
  "predict.order.shares": "份额",
  "predict.order.available": "可用 {amount}",
  "predict.order.holding": "持有 {shares} 份",
  "predict.order.estShares": "预计成交份额",
  "predict.order.avgPrice": "平均成交价",
  "predict.order.total": "订单金额",
  "predict.order.proceeds": "预计回款",
  "predict.order.tif": "有效期",
  "predict.order.gtc": "撤单前有效 (GTC)",
  "predict.order.gtd": "指定日期前有效 (GTD)",
  "predict.order.fee": "手续费 {pct}",
  "predict.order.payout": "若结果为 {outcome} 可得",
  "predict.order.submitBuy": "买入 {outcome} · {amount}",
  "predict.order.submitSell": "卖出 {outcome} · {shares} 份",
  "predict.order.submitLimit": "挂单买入 {outcome} · {shares} 份 @ {price}",
  "predict.order.marketNote": "市价单立即按盘口最优价成交，价格以实际成交为准",
  "predict.order.limitNote":
    "限价单进入盘口等待成交，支持部分成交；可在持仓 → 挂单中撤销",
  "predict.order.filled": "已成交 {shares} 份 @ {price}",
  "predict.order.filledShares": "已成交 {shares} 份",
  "predict.order.minShares": "最少 {n} 份",
  "predict.order.minAmount": "市价买入至少 {amount}",
  "predict.order.tickHint": "限价须为 {tick}¢ 的整数倍",
  "predict.order.placed": "挂单已提交",
  "predict.order.unfilled": "当前价格没有成交，订单已撤销，可调整后重试",
  "predict.order.insufficient": "余额不足",
  "predict.order.insufficientShares": "持有份额不足",
  "predict.order.closed": "市场已截止",
  "predict.order.shares.unit": "份",
  "predict.settlement.title": "结算进度",
  "predict.settlement.proposed": "商户提交的结果",
  "predict.settlement.step.closed": "交易截止",
  "predict.settlement.step.proposed": "商户已提交结果",
  "predict.settlement.step.awaitingProposal": "等待商户提交结果",
  "predict.settlement.step.dispute": "争议期",
  "predict.settlement.step.arbitration": "等待商户裁决",
  "predict.settlement.step.settle": "自动确认并结算",
  "predict.settlement.remaining": "剩余 {time}",
  "predict.settlement.disputeHint":
    "任何持仓用户可对结果提出争议，需锁定押金。无人争议则到期自动确认。",
  "predict.settlement.settleHint": "赢方每份兑付 1.00 USDC，到「持仓」领取",
  "predict.settlement.yourPosition": "你的持仓",
  "predict.settlement.cost": "成本",
  "predict.settlement.ifHolds": "若维持 {outcome}",
  "predict.settlement.zeroed": "此持仓归零 ({amount})",
  "predict.settlement.wins": "兑付 {amount}",
  "predict.settlement.gotIt": "知道了",
  "predict.settlement.dispute": "提出争议 · 锁定 {bond} 押金",
  "predict.settlement.disputeNote":
    "争议只能发起一次。进入争议后由商户管理员最终裁决，裁决无时限，期间不再接受新争议。",
  "predict.settlement.disputeReason": "争议理由",
  "predict.settlement.disputeSubmitted": "争议已提交，押金已锁定",
  "predict.settlement.settledAs": "结果：{outcome}",
  "predict.positions.title": "持仓",
  "predict.positions.value": "持仓价值",
  "predict.positions.totalPnl": "总盈亏",
  "predict.positions.claimable": "可领取收益",
  "predict.positions.claim": "领取",
  "predict.positions.claimed": "已领取 {amount}",
  "predict.positions.tab.positions": "持仓",
  "predict.positions.tab.orders": "挂单",
  "predict.positions.tab.history": "历史",
  "predict.positions.allMarkets": "全部市场",
  "predict.positions.byValue": "按价值",
  "predict.positions.hideZero": "隐藏已归零",
  "predict.positions.youWon": "你赢了",
  "predict.positions.avg": "均价 {price}",
  "predict.positions.avgTo": "均价 {from} → {to}",
  "predict.positions.shares": "{n} 份",
  "predict.positions.settlementPaused": "结算暂缓",
  "predict.positions.progress": "进度",
  "predict.positions.cancel": "撤单",
  "predict.positions.cancelled": "已撤单",
  "predict.positions.orderRow": "{side} {outcome} · {shares} 份 @ {price}",
  "predict.positions.filled": "已成交 {filled}/{total}",
  "predict.positions.empty": "暂无持仓，去看看热门市场",
  "predict.leaderboard.title": "排行榜",
  "predict.leaderboard.today": "今日",
  "predict.leaderboard.week": "本周",
  "predict.leaderboard.month": "本月",
  "predict.leaderboard.all": "全部",
  "predict.leaderboard.byPnl": "按盈亏",
  "predict.leaderboard.byVolume": "按成交量",
  "predict.leaderboard.updated": "更新于 {time}前",
  "predict.leaderboard.winRate": "胜率 {pct}",
  "predict.leaderboard.myRank": "我的排名 #{rank}",
  "predict.leaderboard.pnl": "盈亏",
  "predict.leaderboard.unranked": "暂未上榜",
  "predict.leaderboard.viewPositions": "查看持仓",
  "predict.leaderboard.connect": "连接钱包查看排名",
  "dex.title": "DEX",
  "dex.marketTitle": "行情",
  "dex.createWallet": "创建钱包",
  "dex.allChains": "全部链",
  "dex.tab.hot": "热门",
  "dex.tab.gainers": "涨幅榜",
  "dex.tab.new": "新币",
  "dex.tab.watchlist": "自选",
  "dex.filter.liquidity": "流动性 > $100K",
  "dex.col.token": "代币 / 市值",
  "dex.col.liquidity": "流动性",
  "dex.col.trend": "走势",
  "dex.col.price": "价格 / 24h",
  "dex.new": "新",
  "dex.liquidity": "流动性",
  "dex.mcap": "市值",
  "dex.volume24h": "24h 成交",
  "dex.holders": "持有人",
  "dex.high24h": "24h 高",
  "dex.low24h": "24h 低",
  "dex.depth": "深度",
  "dex.security": "安全检测",
  "dex.security.passed": "{passed} / {total} 通过",
  "dex.security.openSource": "合约已开源",
  "dex.security.closedSource": "合约未开源",
  "dex.security.noMint": "无增发权限",
  "dex.security.mintable": "可增发",
  "dex.security.tax": "买 / 卖税 {buy} / {sell}",
  "dex.security.top10": "前 10 持仓 {pct}",
  "dex.security.honeypot": "疑似貔貅",
  "dex.security.risk": "该代币未通过全部安全检测，请谨慎交易",
  "dex.contract": "合约地址",
  "dex.tab.trades": "成交",
  "dex.tab.holders": "持有者",
  "dex.tab.info": "信息",
  "dex.trades.time": "时间",
  "dex.trades.type": "类型",
  "dex.trades.amount": "数量",
  "dex.trades.value": "价值",
  "dex.trades.buy": "买入",
  "dex.trades.sell": "卖出",
  "dex.buy": "买入",
  "dex.sell": "卖出",
  "dex.buyHint": "用 {tokens} 兑换",
  "dex.sellHint": "余额 {amount}",
  "dex.watchlistAdded": "已加入自选",
  "swap.title": "兑换",
  "swap.pay": "支付",
  "swap.receive": "获得（预估）",
  "swap.balance": "余额 {amount}",
  "swap.selectToken": "选择代币",
  "swap.rate": "汇率",
  "swap.priceImpact": "价格影响",
  "swap.minReceived": "最少获得",
  "swap.minReceivedWithSlippage": "最少获得（滑点 {pct}）",
  "swap.slippage": "滑点",
  "swap.auto": "自动",
  "swap.networkFee": "网络费",
  "swap.serviceFee": "服务费",
  "swap.included": "已含",
  "swap.route": "路由",
  "swap.routeBest": "{router} 最优报价",
  "swap.hops": "{n} 跳池",
  "swap.quoteRefresh": "报价 {seconds} 秒后自动刷新",
  "swap.quoteValid": "报价 {seconds} 秒内有效，超时将重新报价",
  "swap.requote": "重新报价",
  "swap.submit": "兑换",
  "swap.approve": "授权 {symbol}",
  "swap.approving": "授权中…",
  "swap.approved": "已授权 {symbol}",
  "swap.insufficient": "余额不足，去划转",
  "swap.confirmTitle": "确认兑换",
  "swap.confirm": "确认兑换",
  "swap.recipient": "接收地址",
  "swap.recipientWallet": "DEX 钱包 {address}",
  "swap.confirmNote":
    "确认后由钱包签名并广播，通常 5–15 秒到账；可在兑换记录查看进度",
  "swap.submitted": "已提交，等待链上确认",
  "swap.impactWarn": "获得金额比支付低 {pct}，确认继续？",
  "swap.history": "兑换记录",
  "swap.filter.all": "全部",
  "swap.filter.pending": "进行中",
  "swap.filter.confirmed": "成功",
  "swap.filter.failed": "失败",
  "swap.status.submitted": "已提交",
  "swap.status.confirming": "确认中",
  "swap.status.confirmed": "成功",
  "swap.status.failed": "失败",
  "swap.today": "今天",
  "swap.yesterday": "昨天",
  "dex.swap.failed.slippage": "价格变动超过滑点，交易已回滚，资金未扣除",
  "dex.swap.failed.unknown": "交易失败，资金未扣除",
  "approvals.title": "代币授权管理",
  "approvals.hint": "授权允许合约转走你的代币。不再使用的授权建议撤销。",
  "approvals.unlimited": "无限额度",
  "approvals.approvedAt": "授权于 {date}",
  "approvals.lastUsed": "最近使用 {when}",
  "approvals.unusedDays": "{n} 天未使用",
  "approvals.revoke": "撤销",
  "approvals.revokedPartly": "只撤销了 {done}/{total} 个，请重试剩下的",
  "approvals.revoked": "已撤销授权",
  "approvals.revokeAll": "撤销全部无限额度授权（{n}）",
  "approvals.empty": "暂无授权",
  "profile.connector.metamask": "MetaMask",
  "profile.connector.embedded": "内置钱包",
  "profile.connector.walletconnect": "WalletConnect",
  "profile.connector.okx": "OKX Wallet",
  "profile.connector.trust": "Trust Wallet",
  "profile.chains": "{n} 条链",
  "profile.receiveQr": "收款码",
  "profile.referral": "邀请返佣",
  "profile.referralCount": "已邀请 {n} 人",
  "profile.support": "帮助客服",
  "profile.section.wallet": "钱包",
  "profile.section.mine": "我的",
  "profile.section.more": "更多",
  "profile.wallets": "钱包管理",
  "profile.wallets.hint": "切换、添加或断开已连接的钱包",
  "profile.wallets.count": "{n} 个",
  "profile.appLockOn": "应用锁已开",
  "profile.appLockOff": "应用锁未开",
  "profile.addressBook": "转账地址簿",

  "profile.predictPortfolio": "预测持仓",
  "profile.claimable": "可领取",
  "profile.watchlist": "自选代币",
  "profile.watchlist.count": "{n} 个",
  "profile.history": "交易记录",
  "profile.about": "关于",
  "profile.disconnect": "断开连接并退出",
  "profile.sessionUntil": "会话有效期至 {date}",
  "profile.manageSessions": "管理会话",
  "profile.logoutConfirm": "确定断开连接并退出？",
  "profile.logoutHint": "将清除会话与账户级缓存，保留语言、主题等设备偏好。",
  "settings.notificationsOn": "已开启 {n} 项",
  "settings.predictConfirm.hint": "关闭后点击买 Yes / No 直接提交",
  "settings.orderType.market": "市价",
  "settings.orderType.limit": "限价",
  "settings.slippage.auto": "自动",
  "settings.dexRiskWarning.hint": "安全检测未全部通过时兑换前弹窗",
  "settings.appLock": "应用锁",
  "settings.appLock.hint": "Face ID / PIN，离开 {minutes} 分钟后需解锁",
  "settings.txConfirm": "交易前验证",
  "settings.txConfirm.hint": "下单、兑换、划转前要求 Face ID",
  "settings.newVersion": "发现新版本 {version}",
  "settings.upToDate": "已是最新版本",
  "settings.clearCacheConfirm": "清除图片与行情缓存？不影响登录态与偏好。",
  "settings.cacheCleared": "已清除缓存",
  "settings.footer": "版本 {version} ({build}) · 设备 ID {deviceId}",
  "settings.up": "涨",
  "settings.down": "跌",
  "lang.hint":
    "切换后立即生效，无需重启。行情数据与市场标题中的专有名词保持原文。",
  "appearance.title": "外观",
  "appearance.theme.hint": "跟随系统时，App 随手机系统的深浅色模式自动切换。",
  "appearance.colorScheme.greenUp": "绿涨红跌",
  "appearance.colorScheme.redUp": "红涨绿跌",
  "appearance.colorScheme.hint":
    "影响价格涨跌、K 线、兑换价格影响的颜色。预测市场的 Yes / No 固定为绿 / 红，不受此项影响。",
  "notif.permissionDenied": "系统通知权限已关闭，以下开关不会生效",
  "notif.openSettings": "去开启",
  "notif.enable": "开启通知",
  "notif.section.trading": "交易",
  "notif.section.predict": "预测",
  "notif.section.dex": "兑换与行情",
  "notif.section.other": "其他",
  "notif.orderCancelled": "挂单被撤销",
  "notif.orderCancelled.hint": "心跳超时或市场截止导致的撤单",
  "notif.predictDispute": "争议进展",
  "notif.predictDispute.hint": "结果提交、有人争议、裁决完成",
  "notif.predictClosingSoon": "持仓市场即将截止",
  "notif.predictClosingSoon.hint": "截止前 1 小时",
  "notif.swapResult.label": "兑换完成 / 失败",
  "notif.priceAlert.hint": "自选代币触发设定价格",
  "notif.promo.label": "活动与公告",
  "notif.security.label": "安全提醒",
  "notif.security.hint": "新设备登录、提现申请，不可关闭",
  "notif.securityLocked": "安全提醒不可关闭",
  "notif.dnd": "免打扰时段",
  "security.level.medium": "中",
  "security.level.low": "低",
  "security.protectionsOn": "已开启 {n} 项保护",
  "security.suggest.backup": "建议备份内置钱包的助记词",
  "security.suggest.appLock": "建议开启应用锁",
  "security.suggest.txConfirm": "建议开启交易前验证",
  "security.section.protection": "应用保护",
  "security.section.wallets": "钱包与会话",
  "security.section.funds": "资金安全",
  "security.appLock.hint": "Face ID，失败 3 次回落 PIN",
  "security.autoLock": "自动锁定",
  "security.autoLock.immediate": "立即",
  "security.autoLock.value": "离开 {minutes} 分钟后",
  "security.txConfirm.hint": "下单、兑换、划转、转出",
  "security.largeAmount": "大额转出确认",
  "security.largeAmount.hint": "单笔超过设定值需再次验证",
  "security.connectedWallets": "已连接钱包",
  "security.backup": "备份助记词",
  "security.backup.hint": "内置钱包 {address}",
  "security.notBackedUp": "未备份",
  "security.backedUp": "已备份",
  "security.sessions": "登录会话",
  "security.sessions.value": "本机 · 有效至 {date}",
  "security.whitelist": "转出仅限地址簿",
  "security.whitelist.hint": "开启后只能转到地址簿内地址",
  "security.approvals": "代币授权管理",
  "security.approvals.hint": "查看并撤销 DEX 授权",
  "security.approvals.count": "{n} 项",
  "security.disconnectAll": "断开所有会话",
  "security.disconnectAllConfirm": "断开所有会话并退出？",
  "security.locked.title": "应用已锁定",
  "security.locked.subtitle": "验证身份后继续使用",
  "security.unlock": "解锁",
  "security.unlock.failed": "验证未通过，请重试",
  "security.appLock.unavailable":
    "本机未设置生物识别或锁屏密码，应用锁暂不生效",
  "security.appLock.disableReason": "验证身份以关闭应用锁",
  "security.verify.reason": "验证身份以继续",
  "security.verify.failed": "验证未通过，操作已取消",
  "wallets.title": "钱包管理",
  "wallets.current": "当前使用",
  "wallets.others": "其他钱包",
  "wallets.actions": "{label} 的操作",
  "wallets.copy": "复制地址",
  "wallets.rename": "修改显示名",
  "wallets.explorer": "在区块浏览器查看",
  "wallets.disconnect": "断开此钱包",
  "wallets.disconnectConfirm": "断开 {label}？",
  "wallets.add": "添加钱包",
  "wallets.notBackedUp": "未备份",
  "wallets.hint":
    "切换钱包后，持仓、自选与记录按地址分别显示；预测账户与钱包地址一一对应。",
  "wallets.switched": "已切换到 {label}，请重新签名登录",
  "wallets.renamed": "已更新显示名",
  "wallets.renameFailed": "改名没成功，请重试",
  "wallets.disconnectFailed": "断开没成功，请重试",
  "wallets.switchFailed": "切换钱包没成功，请重试",
  "common.save": "保存",
  "common.saving": "保存中…",
  "common.processing": "处理中…",
  "split.title": "拆分 / 合并",
  "split.split": "拆分",
  "split.merge": "合并",
  "split.market": "市场",
  "split.amount": "数量",
  "split.hint.split":
    "用 USDW 按 1:1 铸造等量 Yes + No 份额（每份合计 1 USDW）",
  "split.hint.merge": "把等量的 Yes + No 份额合并赎回为 USDW",
  "split.available": "可用 {amount}",
  "split.holding": "可合并 {n} 份",
  "split.submitSplit": "拆分 {amount}",
  "split.submitMerge": "合并 {n} 份",
  "split.submitted": "已提交，等待链上确认",
  "backup.title": "备份助记词",
  "backup.step": "第 {n} / {total} 步",
  "backup.heading": "抄写这 12 个单词",
  "backup.hint":
    "按顺序抄写在纸上并妥善保管。任何拿到助记词的人都能控制你的资产。",
  "backup.copy": "复制（60 秒后自动清除剪贴板）",
  "backup.copied": "已复制，60 秒后自动清除",
  "backup.locked": "正在验证身份以读取助记词…",
  "wallet.setup.title": "钱包",
  "wallet.setup.heading": "开始使用你的钱包",
  "wallet.setup.hint": "创建一个新钱包，或用助记词、私钥导入已有钱包。",
  "wallet.setup.custodyNotice":
    "这是自托管钱包：助记词只保存在你的设备上，我们无法替你找回。",
  "wallet.setup.create": "创建新钱包",
  "wallet.setup.createHint": "生成 12 个助记词，并立即完成备份",
  "wallet.setup.creating": "正在创建…",
  "wallet.setup.import": "导入已有钱包",
  "wallet.setup.importHint": "用助记词或私钥恢复",
  "wallet.setup.failed": "创建钱包失败，请重试",
  "wallet.import.title": "导入钱包",
  "wallet.import.tab.mnemonic": "助记词",
  "wallet.import.tab.privateKey": "私钥",
  "wallet.import.mnemonicPlaceholder": "按顺序输入 12 或 24 个词，用空格分隔",
  "wallet.import.privateKeyPlaceholder": "0x 开头的 64 位十六进制私钥",
  "wallet.import.invalidMnemonic": "助记词无效，请检查拼写和顺序",
  "wallet.import.invalidPrivateKey": "私钥无效",
  "wallet.import.duplicate": "这个钱包已经在应用里了",
  "wallet.import.derived": "将导入地址",
  "wallet.import.warning": "请确认周围没有人能看到屏幕",
  "wallet.import.submit": "导入",
  "wallet.import.done": "钱包已导入",
  "walletconnect.title": "扫码连接钱包",
  "walletconnect.hint": "用手机或电脑上的钱包扫描下面的二维码",
  "walletconnect.missingWallet": "没检测到 {wallet}，可以用其他钱包扫码连接",
  "walletconnect.warning":
    "只在你自己的钱包里确认；任何人索要二维码都可能是骗局。",
  "walletconnect.copy": "复制连接码",
  "walletconnect.copied": "已复制连接码",
  "walletconnect.waiting": "等待钱包确认…",
  "backup.revealReason": "查看助记词需要验证身份",
  "backup.revealFailed": "未能读取助记词",
  "backup.retry": "重试",
  "backup.noScreenshot": "本页已禁止截图与录屏；不要拍照，不要发给任何人",
  "backup.next": "我已抄写，开始验证",
  "backup.later": "稍后备份",
  "backup.verifyHeading": "验证助记词",
  "backup.verifyHint": "按提示选出对应位置的单词",
  "backup.wordAt": "第 {n} 个单词",
  "backup.wrong": "选错了，请重新核对",
  "backup.markFailed": "备份状态没保存成功，请重试",
  "backup.done": "备份完成",
  "backup.doneHint": "助记词已确认。你可以在安全中心随时再次查看。",
  "backup.finish": "完成",
  "state.empty": "暂无数据",
  "state.error": "加载失败，请重试",
  "action.retryNow": "重试",
  "home.search": "搜索市场、代币",
  "home.scan": "扫描二维码",
  "home.notifications": "通知",
  "home.quick.predict": "预测市场",
  "home.quick.swap": "兑换",
  "home.quick.rank": "排行榜",
  "home.quick.invite": "邀请返佣",
  "home.quick.help": "帮助",
  "home.quick.more": "更多",
  "home.portfolio": "总资产估值",
  "home.hideBalance": "隐藏资产余额",
  "home.showBalance": "显示资产余额",
  "action.refresh": "刷新配置",
  "action.checkupdate": "检查更新",
  "action.retry": "重新下载",
  "action.details": "查看详情",
  "action.collapse": "收起详情",
  "action.back": "返回",
  "action.close": "关闭",
  "action.later": "稍后处理",
  "theme.system": "跟随系统",
  "theme.light": "浅色",
  "theme.dark": "深色",
  "status.loading": "正在同步应用配置",
  "status.error": "暂时无法获取远程配置",
  "update.modalTitle": "发现新版本 {version}",
  "update.modalMeta": "{size} · 当前 {current}",
  "update.forceSubtitle": "此版本已停止服务，更新后继续使用",
  "update.now": "立即更新",
  "update.later": "稍后再说",
  "update.install": "安装",
  "update.downloading": "下载中 {percent}%",
  "update.downloadFailed": "下载失败，请检查网络后重试",
  "update.openedStore": "已打开更新页面",
  "update.none": "当前已经是最新版本",
  "update.optional": "发现可选更新",
  "update.recommended": "建议升级到最新版本",
  "update.required": "当前版本必须升级后继续使用",
  "update.policy": "版本策略",
  "update.currentVersion": "当前版本",
  "update.minimumVersion": "最低支持",
  "update.latestVersion": "最新版本",
  "update.channel": "分发通道",
  "update.release": "发布记录",
  "update.versionInfo": "版本信息",
  "update.requestId": "请求编号",
  "update.otaTitle": "JS 与资源热更新",
  "update.runtime": "运行时版本",
  "update.checking": "检查中…",
  "update.otaAvailable": "发现兼容更新，准备下载",
  "update.otaDownloading": "正在下载 OTA 更新",
  "update.otaApplying": "正在重启并应用 OTA",
  "update.otaImmediateConfirm":
    "此更新标记为立即应用，只有在你确认后才会重启应用。",
  "update.otaImmediateRequired":
    "更新已下载完成，为保证应用正常运行，需要立即重启应用。重启预计需要几秒钟，请点击下方按钮继续。",
  "update.otaImmediateRequiredLabel": "必须完成更新",
  "update.otaImmediateHint": "请保持网络连接，重启期间请勿退出应用。",
  "update.otaImmediateTitle": "更新已准备好",
  "update.otaImmediateRetryTitle": "更新未应用",
  "update.otaImmediateRetry": "应用更新时遇到问题，请再次点击重启并更新。",
  "update.apply": "重启并应用 OTA",
  "update.applyImmediate": "确认并重启应用",
  "update.rollbackApply": "重启并回到安全版本",
  "update.otaDisabled": "OTA 已被远程策略关闭",
  "update.otaUnavailable": "当前构建未启用 OTA，请使用开发构建或发布版本验证。",
  "update.otaIncompatible": "当前通道或运行时没有兼容的 OTA",
  "update.otaCurrent": "当前已是最新兼容版本",
  "update.otaReadyNextLaunch": "更新已下载，将在下次启动时自动应用",
  "update.otaReadyImmediate": "更新已下载，可由你确认后立即重启应用",
  "update.otaRollback": "检测到 OTA 回退，当前使用安全版本",
  "update.embedded": "内置版本",
  "update.embeddedCurrent": "当前使用 APK 内置版本",
  "update.otaError": "暂时无法检查 OTA，请稍后重试。",
  "update.fullTitle": "全量更新",
  "update.fullDescription":
    "通过当前分发渠道安装签名版本，更新前请确认版本与来源。",
  "update.diagnostics": "诊断信息",
  "update.details": "升级详情",
  "update.notConfigured": "尚未配置",
  "update.fullOpened": "已打开当前分发渠道的升级入口",
  "update.statusPage": "查看服务状态与联系方式",
  "update.fullUnavailable": "当前分发渠道尚未配置可安装地址",
  "update.apkDownloadTitle": "正在准备应用升级",
  "update.apkDownloading": "正在安全下载完整安装包，请保持网络连接。",
  "update.apkDownloadError": "安装包下载失败，请检查网络后重试。",
  "update.apkInstallerOpened": "安装包已下载，已打开系统安装确认页面。",
  "settings.title": "设置",
  "settings.theme": "主题",
  "settings.language": "语言",
  "settings.section.general": "通用",
  "settings.section.notifications": "通知",
  "settings.section.trading": "交易偏好",
  "settings.section.security": "安全",
  "settings.section.about": "关于",
  "settings.colorScheme": "涨跌颜色",
  "settings.quoteCurrency": "计价货币",
  "settings.notifications": "推送通知",
  "settings.notificationsOff": "未开启",
  "settings.predictConfirm": "预测下单前确认",
  "settings.predictOrderType": "预测默认订单类型",
  "settings.dexSlippage": "兑换默认滑点",
  "settings.dexRiskWarning": "高风险代币提醒",
  "settings.securityCenter": "安全中心",
  "settings.checkUpdate": "检查更新",
  "settings.terms": "用户协议",
  "settings.privacy": "隐私政策",
  "settings.clearCache": "清除缓存",
  "settings.followSystemLanguage": "跟随系统语言",
  "settings.languageSwitchRetry": "语言未切换，检查网络后可再次点击重试。",
  "predict.order.title": "确认预测订单",
  "predict.order.estimated": "预计获得",
  "predict.order.confirm": "确认下单",
  "swap.status.success": "成功",
  "assets.locked": "锁定资产",
  "notif.title": "推送通知",
  "notif.orderFilled": "订单成交",
  "notif.predictSettled": "预测结算",
  "notif.predictClaimable": "可领取收益",
  "notif.priceAlert": "价格提醒",
  "security.title": "安全中心",
  "security.level": "安全等级",
  "security.level.high": "高",
  "security.loginHistory": "登录记录",
  "nav.home": "首页",
  "nav.predict": "预测",
  "nav.positions": "持仓",
  "nav.dex": "DEX",
  "nav.market": "行情",
  "nav.swap": "兑换",
  "nav.assets": "资产",
  "assets.title": "我的资产",
  "profile.title": "个人中心",
  "profile.securityCenter": "安全中心",
  "update.noticeTitle": "发现新版本",
  "update.noticeDescription": "新版本已准备好，可查看更新内容后选择升级。",
  "update.viewNow": "查看更新",
  "update.confirmAndDownload": "确认并下载",
  "update.localizationTitle": "语言资源已更新",
  "update.localizationDescription": "新的语言包已准备好，将在下次刷新后生效。",
  "update.brandingTitle": "品牌配置已更新",
  "update.brandingDescription": "新的品牌资源已准备好，将在下次启动时生效。",
  "update.configTitle": "应用配置已更新",
  "update.configDescription": "应用配置已更新，正在后台同步。",
};

const enUS: Record<keyof typeof zhCN, string> = {
  "app.name": "AnyFun",
  "home.update": "App updates",
  "home.market": "Market",
  "home.predict": "Popular predictions",
  "home.viewAll": "View all",
  "home.dexHotTokens": "DEX hot tokens",
  "home.deposit": "Deposit",
  "home.withdraw": "Withdraw",
  "home.transfer": "Transfer",
  "home.support": "Help and support",
  "home.connectWallet": "Connect wallet",
  "home.walletAccount": "Wallet",
  "home.predictAccount": "Predict account",
  "home.claimable": "Claimable",
  "home.volume": "Vol",
  "home.closesIn": "Closes",
  "home.outcomes": "{n} outcomes",
  "login.welcome": "Welcome",
  "login.welcomeTitle": "Connect a wallet to predict and swap",
  "login.welcomeHint":
    "No sign-up. Log in with your wallet address. Markets are open to browse without logging in.",
  "login.createWallet": "Create new wallet",
  "login.createHint": "Takes a minute; seed phrase encrypted on this device",
  "login.importWallet": "Import existing wallet",
  "login.importHint": "Seed phrase or private key",
  "login.useWallet": "Use my wallet",
  "login.useWalletHint": "Sign in with the wallet on this device",
  "login.unavailable": "Not enabled for this tenant",
  "login.notInstalled": "Not installed · tap to scan instead",
  "login.opening": "Opening {wallet}…",
  "login.connectFailed": "Could not connect {wallet}. Try again.",
  "login.connectTimeout": "{wallet} did not confirm in time. Try again.",
  "login.noEnabledChain":
    "{wallet} approved none of the networks enabled on this platform. Switch to a supported network in the wallet and try again.",

  "login.reason": "Confirm the sign-in signature",
  "login.builtin": "Built-in wallet",
  "login.external": "Connect external wallet",
  "login.installed": "Installed",
  "login.otherWallet": "Other wallets",
  "login.otherHint": "Scan to connect · WalletConnect",
  "login.terms": "By continuing you agree to the Terms and Privacy Policy",
  "login.continueTo": "Continue to {action} after login",
  "login.intent.order": "buy {outcome}",
  "login.intent.swap": "swap",
  "login.intent.transfer": "transfer",
  "login.intent.assets": "view assets",
  "login.intent.positions": "view positions",
  "login.intent.watchlist": "sync watchlist",
  "login.confirmTitle": "Confirm login",
  "login.connected": "{wallet} connected",
  "login.signTo": "Sign in to",
  "login.purpose": "Purpose",
  "login.purposeValue": "Prove you own this address",
  "login.validity": "Valid for",
  "login.validityValue": "7 days · sign out anytime",
  "login.fee": "Fee",
  "login.feeValue": "Free · no on-chain transaction",
  "login.signNote":
    "Signing never authorizes a transfer. Make sure the domain matches the app you opened.",
  "login.signAndLogin": "Sign and log in",
  "login.switchWallet": "Use another wallet",
  "login.signing": "Waiting for wallet signature…",
  "login.cancelled": "Login cancelled",
  "login.timeout": "Wallet did not respond. Try another wallet.",
  "login.success": "Logged in",
  "login.balance": "Balance",
  "account.title": "Wallet accounts",
  "account.current": "Current",
  "account.copy": "Copy address",
  "account.copied": "Address copied",
  "common.copyFailed": "Could not copy. Select the text manually.",
  "account.disconnect": "Disconnect",
  "account.disconnected": "Disconnected",
  "account.disconnectFailed": "Could not disconnect. Try again.",
  "account.addWallet": "Add wallet",
  "account.notBackedUp": "Not backed up",
  "common.close": "Close",
  "common.cancel": "Cancel",
  "common.confirm": "Confirm",
  "common.done": "Done",
  "common.max": "Max",
  "assets.totalValue": "Total value",
  "assets.today": "Today",
  "assets.receive": "Receive",
  "assets.send": "Send",
  "assets.transferAction": "Transfer",
  "assets.swap": "Swap",
  "assets.accounts": "Accounts",
  "assets.wallet": "Wallet",
  "assets.predictAccount": "Predict account",
  "assets.chains": "{n} chains",
  "assets.available": "Available",
  "assets.coins": "Coins",
  "assets.hideSmall": "Hide small",
  "assets.lockedInOrders": "In orders",
  "assets.accountTotal": "Account total",
  "assets.withdrawToWallet": "Withdraw to wallet",
  "assets.splitMerge": "Split / Merge",
  "assets.custody": "Held by on-chain contract {address}",
  "assets.walletTotal": "Wallet total",
  "assets.allChains": "All chains",
  "assets.balanceUnavailable.node":
    "Balances on {chain} are unavailable right now: the node did not respond. Other chains are not affected.",
  "assets.balanceUnavailable.endpoints":
    "{chain} has no reachable node, so its balances cannot be read. Other chains are not affected.",
  "assets.balanceUnavailable.retry": "Retry",
  "assets.balanceUnavailable.catalogue":
    "The token catalogue for {chain} is incomplete, so its balances are not shown. Other chains are not affected.",
  "assets.totalPartial":
    "Partial total: excludes unavailable chains and tokens without a price",

  "assets.signInToView": "Log in to see your assets",
  "transfer.title": "Transfer",
  "transfer.from": "From",
  "transfer.to": "To",
  "transfer.token": "Token",
  "transfer.amount": "Amount",
  "transfer.walletAvailable": "Wallet available {amount}",
  "transfer.predictAvailable": "Predict account available {amount}",
  "transfer.networkFee": "Network fee",
  "transfer.confirmDeposit": "Confirm deposit {amount}",
  "transfer.confirmWithdraw": "Confirm withdraw {amount}",
  "transfer.depositTitle": "Deposit {amount}",
  "transfer.insufficient": "Insufficient balance",
  "transfer.swapDirection": "Swap direction",
  "transfer.notEnabled": "Enable the predict account before transferring.",
  "transfer.enableNow": "Enable now",
  "transfer.asset": "Deposit asset",
  "transfer.gasBalance": "Wallet gas",
  "transfer.noGas":
    "Not enough {symbol} in the wallet to pay this deposit's fee",
  "transfer.depositSteps.USDC":
    "2 on-chain transactions: approve USDC, then wrap it into USDW in the predict account. Your wallet pays gas for both.",
  "transfer.depositSteps.USDW":
    "1 on-chain transaction: transfer USDW to the predict account. Your wallet pays gas.",
  "transfer.step.approve": "Approving USDC…",
  "transfer.step.wrap": "Wrapping and depositing…",
  "transfer.step.transfer": "Transferring…",
  "transfer.withdrawTwoPhase":
    "Withdrawals take two steps: start the unwrap, then claim after {delay}. USDC returns to wallet {address}.",
  "transfer.unwrapDelay": "Waiting period",
  "transfer.minWithdraw": "Minimum withdrawal {amount}",
  "transfer.withdrawInitiated":
    "Withdrawal started. Claim below once it matures.",
  "transfer.pendingTitle": "Pending claims",
  "transfer.noPending": "No pending withdrawals",
  "transfer.claimableIn": "Claimable in {countdown}",
  "transfer.claimReady": "Ready to claim",
  "transfer.claim": "Claim",
  "transfer.claimTitle": "Claim {amount}",
  "transfer.claimed": "Claimed. USDC is back in your wallet.",
  "transfer.pendingIndexing":
    "Started on-chain, waiting for the platform to index",
  "transfer.failed": "Transfer failed:",
  "transfer.faucet": "Testnet gas",
  "transfer.faucetClaim": "Claim {amount}",
  "transfer.faucetClaimed": "Already claimed today",
  "transfer.faucetDone": "Testnet gas claimed",
  "transfer.faucetFailed": "Faucet claim failed:",
  "transfer.walletAddress": "Wallet address",
  "assets.predictNotEnabled": "Not enabled · tap to enable",
  "assets.enablePredict": "Enable predict account",
  "assets.safeBalance": "Account balance",
  "predict.enableChip": "Enable",
  "predict.enable.title": "Enable your predict account",
  "predict.enable.intro":
    "The prediction market holds USDW and matches orders in an on-chain account (a Safe) controlled by your wallet address. Enabling takes a few wallet signatures and no gas; finished steps are not repeated.",
  "predict.enable.step.login": "Sign in to the platform (signature)",
  "predict.enable.step.deploySafe": "Create the on-chain account (Safe)",
  "predict.enable.step.clobKey": "Create trading credentials (signature)",
  "predict.enable.step.approve": "Approve trading contracts (signature)",
  "predict.enable.safe": "Account {address}",
  "predict.enable.run": "Enable",
  "predict.enable.resume": "Continue",
  "predict.enable.complete": "Enabled",
  "predict.enable.later": "Later",
  "predict.enable.done": "Predict account enabled",
  "predict.enable.failed": "Enable failed:",
  "predict.enable.notConfigured":
    "This app is not connected to a prediction platform yet. Contact the operator.",
  "predict.enable.agreements": "Platform agreements",
  "predict.enable.agree": "I have read and agree to the agreements above",
  "predict.enable.view": "View",
  "predict.enable.agreementRequired": "Required",
  "tx.signed": "Signed",
  "tx.submitted": "Submitted",
  "tx.confirmed": "Confirmed",
  "tx.failed": "Failed",
  "tx.reverted": "Reverted on-chain — the network fee was still spent",
  "tx.minimize": "Minimize and keep browsing",
  "receive.title": "Receive",
  "receive.copy": "Copy address",
  "receive.share": "Share",
  "receive.warn":
    "Only send {chain} assets to this address; assets sent on other networks cannot be recovered",
  "receive.support":
    "Supports {tokens} and any token on {chain}. Usually arrives within 1–3 block confirmations.",
  "receive.copied": "Copied",
  "receive.testnetNotice":
    "This is a testnet address. Testnet assets have no real value; do not send mainnet assets to it.",
  "receive.tokenSeparator": ", ",
  "receive.noChain":
    "No network to receive on: none of the networks this wallet approved is enabled on this platform.",
  "send.title": "Send",
  "send.address": "Recipient address",
  "send.tokenContract": "Token contract",
  "send.nativeToken": "Native token (no contract)",
  "send.impersonationWarning":
    "This is not the platform-verified {symbol}: its contract address differs from the mainstream {symbol}. Check the contract address above character by character before sending.",
  "send.checkAddress":
    "Transfers cannot be undone. Check the full address character by character.",
  "send.addressPlaceholder": "Paste or scan an address",
  "send.paste": "Paste",
  "send.clear": "Clear",
  "send.recent": "Recent recipients",
  "send.recentEmpty":
    "No sends yet. Addresses you send to will show up here for quick reuse.",
  "send.pickToken": "Choose a token to send",
  "send.available": "Available",
  "send.noBalanceOnChain": "Nothing to send on this chain",
  "send.loadingBalances": "Loading balances…",
  "send.scan": "Scan",
  "send.scanTitle": "Scan recipient address",
  "send.scanHint": "Point at the recipient's address QR code",
  "send.scanNotAddress": "This QR code does not contain a wallet address",
  "send.scanTorch": "Torch",
  "send.scanPermissionTitle": "Camera access needed",
  "send.scanPermissionBody":
    "Scanning an address QR code uses the camera. Allow camera access for this app in system settings.",
  "send.scanOpenSettings": "Open settings",
  "send.scanChainMismatch":
    "This QR code is for the {scanned} network, but the selected token is on {current}. Confirm with the recipient which chain they expect.",
  "send.scanChainUnknown":
    "This QR code names a network (chainId {chainId}) that is not enabled here. Confirm with the recipient.",
  "send.addressValid": "Valid {chain} address",
  "send.addressInvalid": "Invalid address format",
  "send.addressChecksum":
    "Address checksum does not match — a character may have been mistyped",
  "send.addressIsContract":
    "This is the token's own contract address. Anything sent there is lost for good.",
  "send.network": "Network",
  "send.amount": "Amount",
  "send.balance": "Balance {amount}",
  "send.networkFee": "Network fee",
  "send.eta": "Arrives",
  "send.etaValue": "~15s",
  "send.recipientGets": "Recipient gets",
  "send.biometricHint": "Sends over $1,000 require biometric confirmation",
  "send.confirm": "Confirm send {amount}",
  "send.confirmTitle": "Confirm send",
  "send.submitted": "Send submitted",
  "send.failed": "Send failed",
  "send.feeEstimating": "Estimating…",
  "send.feeUnavailable": "Estimate unavailable",
  "send.feeRequired":
    "The network fee cannot be estimated right now, so sending is paused. Try again shortly.",
  "send.demoLedger":
    "Demo ledger: this send is recorded on this device only and never reaches the chain.",
  "send.testnetTag": "Testnet",
  "send.noChain": "No network is enabled right now, so nothing can be sent.",
  "send.testnetNotice":
    "This is a test network. Tokens sent here have no real value.",
  "send.confirmInWallet":
    "Switched to your wallet app — confirm there, then come back.",
  "send.error.feeChanged":
    "The network fee rose sharply after you confirmed, so signing was stopped. Please confirm again.",
  "send.error.gas":
    "The network fee is paid in {symbol} and your balance is too low. Top up a little and retry.",
  "send.error.balance": "Insufficient {symbol} balance",
  "send.error.gasAnomaly":
    "Sending {symbol} would use an abnormal amount of gas, so it was blocked. The token contract may be malicious.",
  "send.error.network":
    "Cannot reach a chain node. Check your connection and retry.",
  "send.error.node":
    "The node rejected this transaction. Please try again later.",
  "send.error.chainEndpoints":
    "This network has no reachable node right now. Please try again later.",
  "send.error.chainDisabled": "This network is disabled on this platform.",
  "send.error.tokenMismatch":
    "This token's contract details do not match our records, so the send was blocked. Please contact support.",
  "send.error.noKey":
    "This device has no key for that account, so it cannot sign. Import the wallet again.",
  "send.error.rejected": "Cancelled — nothing was sent",
  "send.error.authFailed": "Verification failed — nothing was sent",
  "send.error.timeout":
    "The wallet did not respond. Open your wallet app to confirm.",
  "send.error.unsafe":
    "The transaction was incomplete and signing was blocked. Nothing was sent.",
  "predict.title": "Predict",
  "predict.topUp": "Top up",
  "predict.sort.volume": "Volume",
  "predict.sort.endingSoon": "Ending soon",
  "predict.sort.newest": "Newest",
  "predict.special": "Special",
  "predict.outcomes": "{n} outcomes",
  "predict.volume": "Vol {amount}",
  "predict.holders": "{n} holders",
  "predict.closesAt": "Closes {time}",
  "predict.closesIn": "Closes {time}",
  "predict.closedAt": "Closed {time}",
  "predict.kickoff": "Kicks off {time}",
  "predict.draw": "Draw",
  "predict.probability": "chance",
  "predict.yesProbability": "Yes chance",
  "predict.buy": "Buy",
  "predict.sell": "Sell",
  "predict.win1": "Win $1.00",
  "predict.maxReturn": "Up to {pct}",
  "predict.today": "Today",
  "predict.status.trading": "Trading",
  "predict.status.awaiting_result": "Closed · awaiting result",
  "predict.status.result_proposed": "Result pending confirmation",
  "predict.status.disputed": "Disputed",
  "predict.status.arbitrating": "Awaiting ruling",
  "predict.status.settled": "Settled",
  "predict.tab.book": "Book",
  "predict.tab.trades": "Trades",
  "predict.tab.rules": "Rules",
  "predict.tab.holders": "Holders",
  "predict.book.yes": "Yes book",
  "predict.book.spread": "Spread {spread}",
  "predict.book.tick": "Depth {tick}",
  "predict.book.bid": "Bid",
  "predict.book.ask": "Ask",
  "predict.book.shares": "Shares",
  "predict.rules.title": "Resolution",
  "predict.rules.resolver": "Resolver",
  "predict.rules.resolverValue": "Merchant admin",
  "predict.rules.disputeWindow": "Dispute window",
  "predict.rules.disputeWindowValue": "{hours}h after result is posted",
  "predict.rules.fee": "Fee",
  "predict.rules.feeValue": "{pct} of volume",
  "predict.order.market": "Market",
  "predict.order.limit": "Limit",
  "predict.order.limitPrice": "Limit price (¢)",
  "predict.order.bookHint": "Book {bid} / {ask}",
  "predict.order.amount": "Amount",
  "predict.order.shares": "Shares",
  "predict.order.available": "Available {amount}",
  "predict.order.holding": "Holding {shares} shares",
  "predict.order.estShares": "Est. shares",
  "predict.order.avgPrice": "Avg. price",
  "predict.order.total": "Order total",
  "predict.order.proceeds": "Est. proceeds",
  "predict.order.tif": "Time in force",
  "predict.order.gtc": "Good till cancelled (GTC)",
  "predict.order.gtd": "Good till date (GTD)",
  "predict.order.fee": "Fee {pct}",
  "predict.order.payout": "If {outcome} wins you get",
  "predict.order.submitBuy": "Buy {outcome} · {amount}",
  "predict.order.submitSell": "Sell {outcome} · {shares} shares",
  "predict.order.submitLimit": "Place buy {outcome} · {shares} @ {price}",
  "predict.order.marketNote":
    "Market orders fill at the best book price; the final price is the executed price",
  "predict.order.limitNote":
    "Limit orders wait in the book and may partially fill; cancel under Positions → Orders",
  "predict.order.filled": "Filled {shares} shares @ {price}",
  "predict.order.filledShares": "Filled {shares} shares",
  "predict.order.minShares": "Minimum {n} shares",
  "predict.order.minAmount": "Market buys need at least {amount}",
  "predict.order.tickHint": "Limit price must be a multiple of {tick}¢",
  "predict.order.placed": "Order placed",
  "predict.order.unfilled":
    "Nothing filled at the current price; the order was cancelled",
  "predict.order.insufficient": "Insufficient balance",
  "predict.order.insufficientShares": "Not enough shares",
  "predict.order.closed": "Market closed",
  "predict.order.shares.unit": "shares",
  "predict.settlement.title": "Settlement",
  "predict.settlement.proposed": "Result posted by merchant",
  "predict.settlement.step.closed": "Trading closed",
  "predict.settlement.step.proposed": "Merchant posted result",
  "predict.settlement.step.awaitingProposal": "Waiting for merchant result",
  "predict.settlement.step.dispute": "Dispute window",
  "predict.settlement.step.arbitration": "Awaiting merchant ruling",
  "predict.settlement.step.settle": "Auto-confirm and settle",
  "predict.settlement.remaining": "{time} left",
  "predict.settlement.disputeHint":
    "Any holder can dispute the result by locking a bond. Without a dispute the result confirms automatically.",
  "predict.settlement.settleHint":
    "Winning shares pay 1.00 USDC each; claim under Positions",
  "predict.settlement.yourPosition": "Your position",
  "predict.settlement.cost": "Cost",
  "predict.settlement.ifHolds": "If {outcome} holds",
  "predict.settlement.zeroed": "This position goes to zero ({amount})",
  "predict.settlement.wins": "Pays {amount}",
  "predict.settlement.gotIt": "Got it",
  "predict.settlement.dispute": "Dispute · lock {bond} bond",
  "predict.settlement.disputeNote":
    "Only one dispute can be raised. The merchant admin then rules with no time limit; no further disputes are accepted.",
  "predict.settlement.disputeReason": "Reason",
  "predict.settlement.disputeSubmitted": "Dispute submitted, bond locked",
  "predict.settlement.settledAs": "Result: {outcome}",
  "predict.positions.title": "Positions",
  "predict.positions.value": "Positions value",
  "predict.positions.totalPnl": "Total P&L",
  "predict.positions.claimable": "Claimable",
  "predict.positions.claim": "Claim",
  "predict.positions.claimed": "Claimed {amount}",
  "predict.positions.tab.positions": "Positions",
  "predict.positions.tab.orders": "Orders",
  "predict.positions.tab.history": "History",
  "predict.positions.allMarkets": "All markets",
  "predict.positions.byValue": "By value",
  "predict.positions.hideZero": "Hide zeroed",
  "predict.positions.youWon": "You won",
  "predict.positions.avg": "Avg {price}",
  "predict.positions.avgTo": "Avg {from} → {to}",
  "predict.positions.shares": "{n} shares",
  "predict.positions.settlementPaused": "Settlement paused",
  "predict.positions.progress": "Progress",
  "predict.positions.cancel": "Cancel",
  "predict.positions.cancelled": "Order cancelled",
  "predict.positions.orderRow": "{side} {outcome} · {shares} @ {price}",
  "predict.positions.filled": "Filled {filled}/{total}",
  "predict.positions.empty": "No positions yet — explore trending markets",
  "predict.leaderboard.title": "Leaderboard",
  "predict.leaderboard.today": "Today",
  "predict.leaderboard.week": "Week",
  "predict.leaderboard.month": "Month",
  "predict.leaderboard.all": "All",
  "predict.leaderboard.byPnl": "By P&L",
  "predict.leaderboard.byVolume": "By volume",
  "predict.leaderboard.updated": "Updated {time} ago",
  "predict.leaderboard.winRate": "Win rate {pct}",
  "predict.leaderboard.myRank": "My rank #{rank}",
  "predict.leaderboard.pnl": "P&L",
  "predict.leaderboard.unranked": "Not ranked yet",
  "predict.leaderboard.viewPositions": "View positions",
  "predict.leaderboard.connect": "Connect wallet to see your rank",
  "dex.title": "DEX",
  "dex.marketTitle": "Markets",
  "dex.createWallet": "Create wallet",
  "dex.allChains": "All chains",
  "dex.tab.hot": "Hot",
  "dex.tab.gainers": "Gainers",
  "dex.tab.new": "New",
  "dex.tab.watchlist": "Watchlist",
  "dex.filter.liquidity": "Liquidity > $100K",
  "dex.col.token": "Token / Mcap",
  "dex.col.liquidity": "Liquidity",
  "dex.col.trend": "Trend",
  "dex.col.price": "Price / 24h",
  "dex.new": "New",
  "dex.liquidity": "Liquidity",
  "dex.mcap": "Market cap",
  "dex.volume24h": "24h volume",
  "dex.holders": "Holders",
  "dex.high24h": "24h high",
  "dex.low24h": "24h low",
  "dex.depth": "Depth",
  "dex.security": "Security checks",
  "dex.security.passed": "{passed} / {total} passed",
  "dex.security.openSource": "Verified source",
  "dex.security.closedSource": "Unverified source",
  "dex.security.noMint": "No mint authority",
  "dex.security.mintable": "Mintable",
  "dex.security.tax": "Buy / sell tax {buy} / {sell}",
  "dex.security.top10": "Top 10 hold {pct}",
  "dex.security.honeypot": "Possible honeypot",
  "dex.security.risk":
    "This token failed some security checks. Trade with care.",
  "dex.contract": "Contract",
  "dex.tab.trades": "Trades",
  "dex.tab.holders": "Holders",
  "dex.tab.info": "Info",
  "dex.trades.time": "Time",
  "dex.trades.type": "Type",
  "dex.trades.amount": "Amount",
  "dex.trades.value": "Value",
  "dex.trades.buy": "Buy",
  "dex.trades.sell": "Sell",
  "dex.buy": "Buy",
  "dex.sell": "Sell",
  "dex.buyHint": "Pay with {tokens}",
  "dex.sellHint": "Balance {amount}",
  "dex.watchlistAdded": "Added to watchlist",
  "swap.title": "Swap",
  "swap.pay": "Pay",
  "swap.receive": "Receive (est.)",
  "swap.balance": "Balance {amount}",
  "swap.selectToken": "Select token",
  "swap.rate": "Rate",
  "swap.priceImpact": "Price impact",
  "swap.minReceived": "Minimum received",
  "swap.minReceivedWithSlippage": "Minimum received (slippage {pct})",
  "swap.slippage": "Slippage",
  "swap.auto": "Auto",
  "swap.networkFee": "Network fee",
  "swap.serviceFee": "Service fee",
  "swap.included": "Included",
  "swap.route": "Route",
  "swap.routeBest": "Best quote via {router}",
  "swap.hops": "{n} hop",
  "swap.quoteRefresh": "Quote refreshes in {seconds}s",
  "swap.quoteValid": "Quote valid for {seconds}s, then re-quoted",
  "swap.requote": "Re-quote",
  "swap.submit": "Swap",
  "swap.approve": "Approve {symbol}",
  "swap.approving": "Approving…",
  "swap.approved": "{symbol} approved",
  "swap.insufficient": "Insufficient balance · transfer",
  "swap.confirmTitle": "Confirm swap",
  "swap.confirm": "Confirm swap",
  "swap.recipient": "Recipient",
  "swap.recipientWallet": "DEX wallet {address}",
  "swap.confirmNote":
    "Your wallet signs and broadcasts; usually lands in 5–15s. Track it under swap history.",
  "swap.submitted": "Submitted, awaiting confirmation",
  "swap.impactWarn": "You receive {pct} less than you pay. Continue?",
  "swap.history": "Swap history",
  "swap.filter.all": "All",
  "swap.filter.pending": "Pending",
  "swap.filter.confirmed": "Success",
  "swap.filter.failed": "Failed",
  "swap.status.submitted": "Submitted",
  "swap.status.confirming": "Confirming",
  "swap.status.confirmed": "Success",
  "swap.status.failed": "Failed",
  "swap.today": "Today",
  "swap.yesterday": "Yesterday",
  "dex.swap.failed.slippage":
    "Price moved beyond slippage; reverted, no funds taken",
  "dex.swap.failed.unknown": "Transaction failed; no funds taken",
  "approvals.title": "Token approvals",
  "approvals.hint":
    "Approvals let contracts move your tokens. Revoke the ones you no longer use.",
  "approvals.unlimited": "Unlimited",
  "approvals.approvedAt": "Approved {date}",
  "approvals.lastUsed": "Last used {when}",
  "approvals.unusedDays": "Unused for {n} days",
  "approvals.revoke": "Revoke",
  "approvals.revokedPartly": "Revoked {done}/{total}. Try the rest again.",
  "approvals.revoked": "Approval revoked",
  "approvals.revokeAll": "Revoke all unlimited approvals ({n})",
  "approvals.empty": "No approvals",
  "profile.connector.metamask": "MetaMask",
  "profile.connector.embedded": "Built-in wallet",
  "profile.connector.walletconnect": "WalletConnect",
  "profile.connector.okx": "OKX Wallet",
  "profile.connector.trust": "Trust Wallet",
  "profile.chains": "{n} chains",
  "profile.receiveQr": "Receive",
  "profile.referral": "Referral",
  "profile.referralCount": "{n} invited",
  "profile.support": "Support",
  "profile.section.wallet": "Wallet",
  "profile.section.mine": "Mine",
  "profile.section.more": "More",
  "profile.wallets": "Manage wallets",
  "profile.wallets.hint": "Switch, add or disconnect wallets",
  "profile.wallets.count": "{n}",
  "profile.appLockOn": "App lock on",
  "profile.appLockOff": "App lock off",
  "profile.addressBook": "Address book",

  "profile.predictPortfolio": "Predict positions",
  "profile.claimable": "Claimable",
  "profile.watchlist": "Watchlist",
  "profile.watchlist.count": "{n}",
  "profile.history": "History",
  "profile.about": "About",
  "profile.disconnect": "Disconnect and sign out",
  "profile.sessionUntil": "Session valid until {date}",
  "profile.manageSessions": "Manage sessions",
  "profile.logoutConfirm": "Disconnect and sign out?",
  "profile.logoutHint":
    "Clears the session and account cache; device preferences like language and theme are kept.",
  "settings.notificationsOn": "{n} on",
  "settings.predictConfirm.hint":
    "When off, tapping Buy Yes / No submits immediately",
  "settings.orderType.market": "Market",
  "settings.orderType.limit": "Limit",
  "settings.slippage.auto": "Auto",
  "settings.dexRiskWarning.hint":
    "Warn before swapping tokens that fail security checks",
  "settings.appLock": "App lock",
  "settings.appLock.hint": "Face ID / PIN after {minutes} min away",
  "settings.txConfirm": "Verify before trading",
  "settings.txConfirm.hint":
    "Require Face ID before orders, swaps and transfers",
  "settings.newVersion": "Version {version} available",
  "settings.upToDate": "You're up to date",
  "settings.clearCacheConfirm":
    "Clear image and market cache? Login and preferences are kept.",
  "settings.cacheCleared": "Cache cleared",
  "settings.footer": "Version {version} ({build}) · Device ID {deviceId}",
  "settings.up": "Up",
  "settings.down": "Down",
  "lang.hint":
    "Takes effect immediately. Market data and proper nouns stay in their original language.",
  "appearance.title": "Appearance",
  "appearance.theme.hint":
    "With System, the app follows your phone's light / dark mode.",
  "appearance.colorScheme.greenUp": "Green up / red down",
  "appearance.colorScheme.redUp": "Red up / green down",
  "appearance.colorScheme.hint":
    "Affects price changes, candles and swap price impact. Predict Yes / No stay green / red.",
  "notif.permissionDenied":
    "Notifications are off in system settings; these switches won't take effect",
  "notif.openSettings": "Open settings",
  "notif.enable": "Enable notifications",
  "notif.section.trading": "Trading",
  "notif.section.predict": "Predict",
  "notif.section.dex": "Swap & markets",
  "notif.section.other": "Other",
  "notif.orderCancelled": "Order cancelled",
  "notif.orderCancelled.hint": "Cancelled by heartbeat timeout or market close",
  "notif.predictDispute": "Dispute updates",
  "notif.predictDispute.hint": "Result posted, disputed, ruling made",
  "notif.predictClosingSoon": "Held market closing soon",
  "notif.predictClosingSoon.hint": "1 hour before close",
  "notif.swapResult.label": "Swap completed / failed",
  "notif.priceAlert.hint": "Watchlist token hits your price",
  "notif.promo.label": "Promotions & announcements",
  "notif.security.label": "Security alerts",
  "notif.security.hint": "New device login, withdrawals — cannot be turned off",
  "notif.securityLocked": "Security alerts can't be turned off",
  "notif.dnd": "Do not disturb",
  "security.level.medium": "Medium",
  "security.level.low": "Low",
  "security.protectionsOn": "{n} protections on",
  "security.suggest.backup": "Back up your built-in wallet's seed phrase",
  "security.suggest.appLock": "Turn on app lock",
  "security.suggest.txConfirm": "Turn on verification before trading",
  "security.section.protection": "App protection",
  "security.section.wallets": "Wallets & sessions",
  "security.section.funds": "Funds",
  "security.appLock.hint": "Face ID, falls back to PIN after 3 failures",
  "security.autoLock": "Auto-lock",
  "security.autoLock.immediate": "Immediately",
  "security.autoLock.value": "After {minutes} min away",
  "security.txConfirm.hint": "Orders, swaps, transfers, sends",
  "security.largeAmount": "Large send confirmation",
  "security.largeAmount.hint": "Re-verify above the set amount",
  "security.connectedWallets": "Connected wallets",
  "security.backup": "Back up seed phrase",
  "security.backup.hint": "Built-in wallet {address}",
  "security.notBackedUp": "Not backed up",
  "security.backedUp": "Backed up",
  "security.sessions": "Sessions",
  "security.sessions.value": "This device · until {date}",
  "security.whitelist": "Send to address book only",
  "security.whitelist.hint": "Only addresses in your address book",
  "security.approvals": "Token approvals",
  "security.approvals.hint": "Review and revoke DEX approvals",
  "security.approvals.count": "{n}",
  "security.disconnectAll": "Disconnect all sessions",
  "security.disconnectAllConfirm": "Disconnect all sessions and sign out?",
  "security.locked.title": "App locked",
  "security.locked.subtitle": "Verify your identity to continue",
  "security.unlock": "Unlock",
  "security.unlock.failed": "Verification failed, try again",
  "security.appLock.unavailable":
    "This device has no biometrics or screen lock, so the app lock has no effect",
  "security.appLock.disableReason":
    "Verify your identity to turn off the app lock",
  "security.verify.reason": "Verify your identity to continue",
  "security.verify.failed": "Verification failed, action cancelled",
  "wallets.title": "Manage wallets",
  "wallets.current": "Current",
  "wallets.others": "Other wallets",
  "wallets.actions": "Actions for {label}",
  "wallets.copy": "Copy address",
  "wallets.rename": "Rename",
  "wallets.explorer": "View on explorer",
  "wallets.disconnect": "Disconnect this wallet",
  "wallets.disconnectConfirm": "Disconnect {label}?",
  "wallets.add": "Add wallet",
  "wallets.notBackedUp": "Not backed up",
  "wallets.hint":
    "After switching, positions, watchlist and history follow the address; the predict account maps 1:1 to the wallet.",
  "wallets.switched": "Switched to {label}. Please sign in again.",
  "wallets.renameFailed": "Could not rename. Try again.",
  "wallets.disconnectFailed": "Could not disconnect. Try again.",
  "wallets.switchFailed": "Could not switch wallet. Try again.",
  "wallets.renamed": "Display name updated",
  "common.save": "Save",
  "common.saving": "Saving…",
  "common.processing": "Working…",
  "split.title": "Split / Merge",
  "split.split": "Split",
  "split.merge": "Merge",
  "split.market": "Market",
  "split.amount": "Amount",
  "split.hint.split":
    "Mint equal Yes + No shares from USDW 1:1 (each pair = 1 USDW)",
  "split.hint.merge": "Merge equal Yes + No shares back into USDW",
  "split.available": "Available {amount}",
  "split.holding": "Mergeable {n} shares",
  "split.submitSplit": "Split {amount}",
  "split.submitMerge": "Merge {n} shares",
  "split.submitted": "Submitted, awaiting confirmation",
  "backup.title": "Back up seed phrase",
  "backup.step": "Step {n} of {total}",
  "backup.heading": "Write down these 12 words",
  "backup.hint":
    "Write them down in order and keep them safe. Anyone with the phrase controls your assets.",
  "backup.copy": "Copy (clipboard clears in 60s)",
  "backup.copied": "Copied. Clears in 60s.",
  "backup.locked": "Verifying your identity to read the phrase…",
  "wallet.setup.title": "Wallet",
  "wallet.setup.heading": "Set up your wallet",
  "wallet.setup.hint":
    "Create a new wallet, or import one with a recovery phrase or private key.",
  "wallet.setup.custodyNotice":
    "This is a self-custodial wallet: the recovery phrase stays on your device and we cannot recover it for you.",
  "wallet.setup.create": "Create a new wallet",
  "wallet.setup.createHint": "Generate a 12-word phrase and back it up now",
  "wallet.setup.creating": "Creating…",
  "wallet.setup.import": "Import an existing wallet",
  "wallet.setup.importHint": "Restore with a recovery phrase or private key",
  "wallet.setup.failed": "Could not create the wallet. Try again.",
  "wallet.import.title": "Import wallet",
  "wallet.import.tab.mnemonic": "Recovery phrase",
  "wallet.import.tab.privateKey": "Private key",
  "wallet.import.mnemonicPlaceholder":
    "Enter your 12 or 24 words in order, separated by spaces",
  "wallet.import.privateKeyPlaceholder":
    "A 64-character hex private key starting with 0x",
  "wallet.import.invalidMnemonic":
    "That recovery phrase is not valid — check the spelling and order",
  "wallet.import.invalidPrivateKey": "That private key is not valid",
  "wallet.import.duplicate": "That wallet is already in the app",
  "wallet.import.derived": "Address to import",
  "wallet.import.warning": "Make sure nobody can see your screen",
  "wallet.import.submit": "Import",
  "wallet.import.done": "Wallet imported",
  "walletconnect.title": "Scan to connect",
  "walletconnect.hint":
    "Scan this code with the wallet on your phone or computer",
  "walletconnect.missingWallet":
    "{wallet} was not found on this device. You can scan with another wallet.",
  "walletconnect.warning":
    "Only approve this in your own wallet. Anyone asking you for this code is likely a scam.",
  "walletconnect.copy": "Copy connection code",
  "walletconnect.copied": "Connection code copied",
  "walletconnect.waiting": "Waiting for the wallet to approve…",
  "backup.revealReason": "Verify your identity to view the recovery phrase",
  "backup.revealFailed": "Could not read the recovery phrase",
  "backup.retry": "Try again",
  "backup.noScreenshot":
    "Screenshots and recording are blocked here; don't photograph or share it",
  "backup.next": "I've written it down, verify",
  "backup.later": "Back up later",
  "backup.verifyHeading": "Verify seed phrase",
  "backup.verifyHint": "Pick the word for each position",
  "backup.wordAt": "Word #{n}",
  "backup.wrong": "Wrong word, please check again",
  "backup.markFailed": "Could not save the backup state. Try again.",
  "backup.done": "Backup complete",
  "backup.doneHint":
    "Seed phrase confirmed. You can review it any time in Security Center.",
  "backup.finish": "Done",
  "state.empty": "Nothing here yet",
  "state.error": "Failed to load, please retry",
  "action.retryNow": "Retry",
  "home.search": "Search markets and tokens",
  "home.scan": "Scan QR code",
  "home.notifications": "Notifications",
  "home.quick.predict": "Predictions",
  "home.quick.swap": "Swap",
  "home.quick.rank": "Leaderboard",
  "home.quick.invite": "Referral",
  "home.quick.help": "Help",
  "home.quick.more": "More",
  "home.portfolio": "Total portfolio value",
  "home.hideBalance": "Hide asset balance",
  "home.showBalance": "Show asset balance",
  "action.refresh": "Refresh configuration",
  "action.checkupdate": "Check for updates",
  "action.retry": "Download again",
  "action.details": "View details",
  "action.collapse": "Hide details",
  "action.back": "Back",
  "action.close": "Close",
  "action.later": "Later",
  "theme.system": "System",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "status.loading": "Syncing app configuration",
  "status.error": "Remote configuration is temporarily unavailable",
  "update.modalTitle": "Version {version} available",
  "update.modalMeta": "{size} · Current {current}",
  "update.forceSubtitle":
    "This version is no longer supported. Update to continue.",
  "update.now": "Update now",
  "update.later": "Later",
  "update.install": "Install",
  "update.downloading": "Downloading {percent}%",
  "update.downloadFailed": "Download failed. Check your network and try again.",
  "update.openedStore": "Opened the update page",
  "update.none": "You already have the latest version",
  "update.optional": "An optional update is available",
  "update.recommended": "Updating to the latest version is recommended",
  "update.required": "Update is required to continue",
  "update.policy": "Version policy",
  "update.currentVersion": "Current version",
  "update.minimumVersion": "Minimum supported",
  "update.latestVersion": "Latest version",
  "update.channel": "Distribution channel",
  "update.release": "Release",
  "update.versionInfo": "Version information",
  "update.requestId": "Request ID",
  "update.otaTitle": "JS and asset hot update",
  "update.runtime": "Runtime version",
  "update.checking": "Checking…",
  "update.otaAvailable": "A compatible update is available",
  "update.otaDownloading": "Downloading OTA update",
  "update.otaApplying": "Restarting to apply OTA",
  "update.otaImmediateConfirm":
    "This update is marked for immediate application. The app will restart only after you confirm.",
  "update.otaImmediateRequired":
    "The update is ready and requires an immediate restart. This should take a few seconds; tap the button below to continue.",
  "update.otaImmediateRequiredLabel": "Update required",
  "update.otaImmediateHint":
    "Keep your network connection available and do not close the app while it restarts.",
  "update.otaImmediateTitle": "Update ready",
  "update.otaImmediateRetryTitle": "Update not applied",
  "update.otaImmediateRetry":
    "The update could not be applied. Tap the button to retry restarting and applying it.",
  "update.apply": "Restart and apply OTA",
  "update.applyImmediate": "Confirm and restart app",
  "update.rollbackApply": "Restart and return to the safe version",
  "update.otaDisabled": "OTA is disabled by remote policy",
  "update.otaUnavailable":
    "OTA is unavailable in this build. Use a development or release build.",
  "update.otaIncompatible":
    "No compatible OTA exists for this channel and runtime",
  "update.otaCurrent": "This runtime is up to date",
  "update.otaReadyNextLaunch":
    "Update downloaded and will be applied on the next launch",
  "update.otaReadyImmediate":
    "Update downloaded and can be applied after you confirm a restart",
  "update.otaRollback":
    "An OTA rollback was detected; the safe version is active",
  "update.embedded": "Embedded version",
  "update.embeddedCurrent": "Running the version embedded in this build",
  "update.otaError": "Unable to check OTA right now. Try again later.",
  "update.fullTitle": "Full update",
  "update.fullDescription":
    "Install a signed version through the current distribution channel.",
  "update.diagnostics": "Diagnostics",
  "update.details": "Update details",
  "update.notConfigured": "Not configured",
  "update.fullOpened": "Opened the update entry for this distribution channel",
  "update.statusPage": "Service status and contact",
  "update.fullUnavailable":
    "No install URL is configured for this distribution channel",
  "update.apkDownloadTitle": "Preparing app update",
  "update.apkDownloading":
    "Downloading the signed APK. Keep the network connection active.",
  "update.apkDownloadError":
    "The APK download failed. Check your connection and try again.",
  "update.apkInstallerOpened":
    "The APK is ready and the system installation confirmation was opened.",
  "settings.title": "Settings",
  "settings.theme": "Theme",
  "settings.language": "Language",
  "settings.section.general": "General",
  "settings.section.notifications": "Notifications",
  "settings.section.trading": "Trading preferences",
  "settings.section.security": "Security",
  "settings.section.about": "About",
  "settings.colorScheme": "Price colors",
  "settings.quoteCurrency": "Quote currency",
  "settings.notifications": "Push notifications",
  "settings.notificationsOff": "Off",
  "settings.predictConfirm": "Confirm prediction orders",
  "settings.predictOrderType": "Default prediction order type",
  "settings.dexSlippage": "Default swap slippage",
  "settings.dexRiskWarning": "High-risk token warning",
  "settings.securityCenter": "Security center",
  "settings.checkUpdate": "Check for updates",
  "settings.terms": "Terms of service",
  "settings.privacy": "Privacy policy",
  "settings.clearCache": "Clear cache",
  "settings.followSystemLanguage": "Follow system language",
  "settings.languageSwitchRetry":
    "The language was not changed. Check your connection and try again.",
  "predict.buyYes": "Buy Yes",
  "predict.buyNo": "Buy No",
  "predict.order.title": "Confirm prediction order",
  "predict.order.estimated": "Estimated payout",
  "predict.order.confirm": "Confirm order",
  "swap.status.success": "Success",
  "assets.locked": "Locked assets",
  "notif.title": "Push notifications",
  "notif.orderFilled": "Order filled",
  "notif.predictSettled": "Prediction settled",
  "notif.predictClaimable": "Claimable return",
  "notif.priceAlert": "Price alerts",
  "security.title": "Security center",
  "security.level": "Security level",
  "security.level.high": "High",
  "security.loginHistory": "Login history",
  "nav.home": "Home",
  "nav.predict": "Predict",
  "nav.positions": "Positions",
  "nav.dex": "DEX",
  "nav.market": "Markets",
  "nav.swap": "Swap",
  "nav.assets": "Assets",
  "assets.title": "My assets",
  "profile.title": "Profile",
  "profile.securityCenter": "Security center",
  "update.noticeTitle": "New version available",
  "update.noticeDescription":
    "A new version is ready. Review the changes before updating.",
  "update.viewNow": "View update",
  "update.confirmAndDownload": "Confirm and download",
  "update.localizationTitle": "Language resources updated",
  "update.localizationDescription":
    "New language resources are ready and will apply after the next refresh.",
  "update.brandingTitle": "Branding updated",
  "update.brandingDescription":
    "New branding resources are ready and will apply on the next launch.",
  "update.configTitle": "App configuration updated",
  "update.configDescription":
    "App configuration changed and is syncing in the background.",
};

export function createFallbackConfig(locale: SupportedLocale): BootstrapConfig {
  return {
    schemaVersion: 1,
    configVersion: "embedded-1",
    generatedAt: "2026-08-21T00:00:00.000Z",
    ttlSeconds: 300,
    requestId: "offline",
    localization: {
      selectedLocale: locale,
      refreshIntervalSeconds: 21_600,
      fallbackLocale: "zh-CN",
      supportedLocales: ["zh-CN", "en-US"],
      localeCatalog: [
        { code: "zh-CN", label: "简体中文", nativeName: "中文" },
        { code: "en-US", label: "English", nativeName: "English" },
      ],
      messagesVersion: "embedded-1",
      messages: normalizeMessages(locale === "en-US" ? enUS : zhCN),
    },
    theme: {
      defaultMode: "system",
      allowUserOverride: true,
      paletteVersion: "embedded-trading-1",
      light,
      dark,
    },
    modules: { predict: true, dex: true },
    // 内置配置里没有租户，也就没有外部服务的关联
    services: {},
    // 内置配置里没有租户，也就没有链、没有目录：钱包界面在收到下发前是空态
    wallet: {
      walletConnectProjectId: "",
      onchainSends: false,
      networks: [],
      tokens: [],
    },
    branding: {
      schemaVersion: 1,
      version: 1,
      enabled: true,
      selectedLocale: locale,
      fallbackLocale: "zh-CN",
      launch: {
        enabled: true,
        minDisplayMs: 700,
        animation: { type: "fade_scale", durationMs: 360 },
        title: locale === "en-US" ? "AnyFun" : "AnyFun",
        subtitle:
          locale === "en-US" ? "Syncing app configuration" : "正在同步应用配置",
        visuals: {
          light: { backgroundColor: light.background },
          dark: { backgroundColor: dark.background },
        },
      },
      cachePolicy: {
        maxBytes: 20 * 1024 * 1024,
        keepVersions: 2,
        staleAfterSeconds: 7 * 24 * 60 * 60,
      },
    },
    features: {
      updateCenter: true,
      otaEnabled: false,
      directUpdateEnabled: appRuntime.platform === "android",
      diagnosticsEnabled: true,
    },
    app: {
      version: appRuntime.version,
      buildNumber: appRuntime.buildNumber,
      platform: appRuntime.platform,
      distribution:
        appRuntime.distributionChannel as BootstrapConfig["app"]["distribution"],
      runtimeVersion: appRuntime.runtimeVersion,
    },
    update: {
      decision: "none",
      minSupportedVersion: appRuntime.version,
      latestVersion: appRuntime.version,
      releaseNotes: [],
      ota: {
        enabled: false,
        channel: "embedded",
        runtimeVersion: appRuntime.runtimeVersion,
        applyStrategy: "next_launch",
        revision: null,
        updateId: null,
        baseReleaseId: null,
        releaseNotes: [],
      },
      full: {
        channel: "development",
        actionUrl: null,
        releaseId: null,
        sha256: null,
        size: null,
      },
    },
    support: {
      diagnosticId: "offline",
      statusPageUrl: "https://status.example.com",
    },
  };
}
