export type RootStackParamList = {
  AppShell: undefined;
  Profile: undefined;
  UpdateCenter: { autoPrompt?: boolean } | undefined;
  Settings: undefined;
  LanguageSettings: undefined;
  AppearanceSettings: undefined;
  PredictEvent: undefined;
  PredictOrder: { side: "yes" | "no" };
  PredictSettlement: undefined;
  DexToken: undefined;
  Swap: undefined;
  SwapHistory: undefined;
  Transfer: { direction?: "deposit" | "withdraw"; amount?: string } | undefined;
  AccountDetail: { kind: "predict" | "wallet" };
  Send: { chain?: "bsc" | "eth" | "base" } | undefined;
  NotificationSettings: undefined;
  About: undefined;
  SecurityCenter: undefined;
};
